package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * AirSterilize generated by hbm2java
 */
public class AirSterilize implements java.io.Serializable
{

	private int id;
	private Date airDate;
	private String lightNo;
	private String times;
	private Character cleanId;
	private String operator;
	private String remark;
	private String recordName;
	private Date recordTime;

	public AirSterilize()
	{
	}

	public AirSterilize(int id, Date airDate, String lightNo)
	{
		this.id = id;
		this.airDate = airDate;
		this.lightNo = lightNo;
	}

	public AirSterilize(int id, Date airDate, String lightNo, String times, Character cleanId, String operator,
			String remark, String recordName, Date recordTime)
	{
		this.id = id;
		this.airDate = airDate;
		this.lightNo = lightNo;
		this.times = times;
		this.cleanId = cleanId;
		this.operator = operator;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Date getAirDate()
	{
		return this.airDate;
	}

	public void setAirDate(Date airDate)
	{
		this.airDate = airDate;
	}

	public String getLightNo()
	{
		return this.lightNo;
	}

	public void setLightNo(String lightNo)
	{
		this.lightNo = lightNo;
	}

	public String getTimes()
	{
		return this.times;
	}

	public void setTimes(String times)
	{
		this.times = times;
	}

	public Character getCleanId()
	{
		return this.cleanId;
	}

	public void setCleanId(Character cleanId)
	{
		this.cleanId = cleanId;
	}

	public String getOperator()
	{
		return this.operator;
	}

	public void setOperator(String operator)
	{
		this.operator = operator;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

}
