package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * CAntiSerum generated by hbm2java
 */
public class CAntiSerum implements java.io.Serializable
{

	private CAntiSerumId id;

	public CAntiSerum()
	{
	}

	public CAntiSerum(CAntiSerumId id)
	{
		this.id = id;
	}

	public CAntiSerumId getId()
	{
		return this.id;
	}

	public void setId(CAntiSerumId id)
	{
		this.id = id;
	}

}
