package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CClient generated by hbm2java
 */
public class CClient implements java.io.Serializable
{

	private int id;
	private String SName;
	private String name;
	private String linkman;
	private String webAddr;
	private String address;
	private String telephone;
	private String zjf;
	private char status;
	private String type;
	private String remark;
	private String recordName;
	private Date recordTime;
	private Set<CEquipment> CEquipments = new HashSet<CEquipment>(0);
	private Set<CReagent> CReagents = new HashSet<CReagent>(0);

	public CClient()
	{
	}

	public CClient(int id, String SName, char status)
	{
		this.id = id;
		this.SName = SName;
		this.status = status;
	}

	public CClient(int id, String SName, String name, String linkman, String webAddr, String address, String telephone,
			String zjf, char status, String type, String remark, String recordName, Date recordTime,
			Set<CEquipment> CEquipments, Set<CReagent> CReagents)
	{
		this.id = id;
		this.SName = SName;
		this.name = name;
		this.linkman = linkman;
		this.webAddr = webAddr;
		this.address = address;
		this.telephone = telephone;
		this.zjf = zjf;
		this.status = status;
		this.type = type;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
		this.CEquipments = CEquipments;
		this.CReagents = CReagents;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getSName()
	{
		return this.SName;
	}

	public void setSName(String SName)
	{
		this.SName = SName;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getLinkman()
	{
		return this.linkman;
	}

	public void setLinkman(String linkman)
	{
		this.linkman = linkman;
	}

	public String getWebAddr()
	{
		return this.webAddr;
	}

	public void setWebAddr(String webAddr)
	{
		this.webAddr = webAddr;
	}

	public String getAddress()
	{
		return this.address;
	}

	public void setAddress(String address)
	{
		this.address = address;
	}

	public String getTelephone()
	{
		return this.telephone;
	}

	public void setTelephone(String telephone)
	{
		this.telephone = telephone;
	}

	public String getZjf()
	{
		return this.zjf;
	}

	public void setZjf(String zjf)
	{
		this.zjf = zjf;
	}

	public char getStatus()
	{
		return this.status;
	}

	public void setStatus(char status)
	{
		this.status = status;
	}

	public String getType()
	{
		return this.type;
	}

	public void setType(String type)
	{
		this.type = type;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public Set<CEquipment> getCEquipments()
	{
		return this.CEquipments;
	}

	public void setCEquipments(Set<CEquipment> CEquipments)
	{
		this.CEquipments = CEquipments;
	}

	public Set<CReagent> getCReagents()
	{
		return this.CReagents;
	}

	public void setCReagents(Set<CReagent> CReagents)
	{
		this.CReagents = CReagents;
	}

}
