package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * CDrRef generated by hbm2java
 */
public class CDrRef implements java.io.Serializable
{

	private int id;
	private String pos;
	private String pcrS;
	private String pcr1;
	private String pcr2;
	private String secore;
	private String remark;
	private Date recordTime;
	private String recordName;

	public CDrRef()
	{
	}

	public CDrRef(int id, String pos, String pcrS, String pcr1, String pcr2, String secore)
	{
		this.id = id;
		this.pos = pos;
		this.pcrS = pcrS;
		this.pcr1 = pcr1;
		this.pcr2 = pcr2;
		this.secore = secore;
	}

	public CDrRef(int id, String pos, String pcrS, String pcr1, String pcr2, String secore, String remark,
			Date recordTime, String recordName)
	{
		this.id = id;
		this.pos = pos;
		this.pcrS = pcrS;
		this.pcr1 = pcr1;
		this.pcr2 = pcr2;
		this.secore = secore;
		this.remark = remark;
		this.recordTime = recordTime;
		this.recordName = recordName;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getPos()
	{
		return this.pos;
	}

	public void setPos(String pos)
	{
		this.pos = pos;
	}

	public String getPcrS()
	{
		return this.pcrS;
	}

	public void setPcrS(String pcrS)
	{
		this.pcrS = pcrS;
	}

	public String getPcr1()
	{
		return this.pcr1;
	}

	public void setPcr1(String pcr1)
	{
		this.pcr1 = pcr1;
	}

	public String getPcr2()
	{
		return this.pcr2;
	}

	public void setPcr2(String pcr2)
	{
		this.pcr2 = pcr2;
	}

	public String getSecore()
	{
		return this.secore;
	}

	public void setSecore(String secore)
	{
		this.secore = secore;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

}
