package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * CEquipment generated by hbm2java
 */
public class CEquipment implements java.io.Serializable
{

	private int id;
	private CClient CClient;
	private String code;
	private String name;
	private String position;
	private String adjustDays;
	private String maintainDays;
	private String factoryNo;
	private String serviceTel;
	private String assetNo;
	private String manager;
	private char status;
	private String remark;
	private String recordName;
	private Date recordTime;

	public CEquipment()
	{
	}

	public CEquipment(int id, String code, String name, char status)
	{
		this.id = id;
		this.code = code;
		this.name = name;
		this.status = status;
	}

	public CEquipment(int id, CClient CClient, String code, String name, String position, String adjustDays,
			String maintainDays, String factoryNo, String serviceTel, String assetNo, String manager, char status,
			String remark, String recordName, Date recordTime)
	{
		this.id = id;
		this.CClient = CClient;
		this.code = code;
		this.name = name;
		this.position = position;
		this.adjustDays = adjustDays;
		this.maintainDays = maintainDays;
		this.factoryNo = factoryNo;
		this.serviceTel = serviceTel;
		this.assetNo = assetNo;
		this.manager = manager;
		this.status = status;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public CClient getCClient()
	{
		return this.CClient;
	}

	public void setCClient(CClient CClient)
	{
		this.CClient = CClient;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getPosition()
	{
		return this.position;
	}

	public void setPosition(String position)
	{
		this.position = position;
	}

	public String getAdjustDays()
	{
		return this.adjustDays;
	}

	public void setAdjustDays(String adjustDays)
	{
		this.adjustDays = adjustDays;
	}

	public String getMaintainDays()
	{
		return this.maintainDays;
	}

	public void setMaintainDays(String maintainDays)
	{
		this.maintainDays = maintainDays;
	}

	public String getFactoryNo()
	{
		return this.factoryNo;
	}

	public void setFactoryNo(String factoryNo)
	{
		this.factoryNo = factoryNo;
	}

	public String getServiceTel()
	{
		return this.serviceTel;
	}

	public void setServiceTel(String serviceTel)
	{
		this.serviceTel = serviceTel;
	}

	public String getAssetNo()
	{
		return this.assetNo;
	}

	public void setAssetNo(String assetNo)
	{
		this.assetNo = assetNo;
	}

	public String getManager()
	{
		return this.manager;
	}

	public void setManager(String manager)
	{
		this.manager = manager;
	}

	public char getStatus()
	{
		return this.status;
	}

	public void setStatus(char status)
	{
		this.status = status;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

}
