package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * CheckBillRec generated by hbm2java
 */
public class CheckBillRec implements java.io.Serializable
{

	private int id;
	private int billId;
	private String billNo;
	private Date operDate;
	private Integer templateId;
	private String operName;
	private String checkName;
	private String bloodType;
	private String rhdRes;
	private String phenotype;
	private String bloodTypeM;
	private String rhdResM;
	private String phenotypeM;
	private String bloodTypeF;
	private String rhdResF;
	private String phenotypeF;
	private String rsYs1;
	private String rsYs2;
	private String rsYs3;
	private String rsYs4;
	private String rsYs5;
	private String rsNj1;
	private String rsNj2;
	private String rsNj3;
	private String rsNj4;
	private String rsNj5;
	private String rsLiss1;
	private String rsLiss2;
	private String rsLiss3;
	private String rsDa;
	private Character ylRs;
	private Character ylRsA;
	private Character ylRsB;
	private Character ylRsOther;
	private String ylRsOtherVal;
	private Character sfRs;
	private Character sfRsA;
	private Character sfRsB;
	private Character sfRsOther;
	private String sfRsOtherVal;
	private Character aboId;
	private String effect;
	private String result1;
	private String result2;
	private String remark;
	private String recordName;
	private Date recordTime;
	private Date checkDate;
	private String editRemark;

	public CheckBillRec()
	{
	}

	public CheckBillRec(int id, int billId, String billNo, Date operDate, String operName)
	{
		this.id = id;
		this.billId = billId;
		this.billNo = billNo;
		this.operDate = operDate;
		this.operName = operName;
	}

	public CheckBillRec(int id, int billId, String billNo, Date operDate, Integer templateId, String operName,
			String checkName, String bloodType, String rhdRes, String phenotype, String bloodTypeM, String rhdResM,
			String phenotypeM, String bloodTypeF, String rhdResF, String phenotypeF, String rsYs1, String rsYs2,
			String rsYs3, String rsYs4, String rsYs5, String rsNj1, String rsNj2, String rsNj3, String rsNj4,
			String rsNj5, String rsLiss1, String rsLiss2, String rsLiss3, String rsDa, Character ylRs, Character ylRsA,
			Character ylRsB, Character ylRsOther, String ylRsOtherVal, Character sfRs, Character sfRsA, Character sfRsB,
			Character sfRsOther, String sfRsOtherVal, Character aboId, String effect, String result1, String result2,
			String remark, String recordName, Date recordTime, Date checkDate, String editRemark)
	{
		this.id = id;
		this.billId = billId;
		this.billNo = billNo;
		this.operDate = operDate;
		this.templateId = templateId;
		this.operName = operName;
		this.checkName = checkName;
		this.bloodType = bloodType;
		this.rhdRes = rhdRes;
		this.phenotype = phenotype;
		this.bloodTypeM = bloodTypeM;
		this.rhdResM = rhdResM;
		this.phenotypeM = phenotypeM;
		this.bloodTypeF = bloodTypeF;
		this.rhdResF = rhdResF;
		this.phenotypeF = phenotypeF;
		this.rsYs1 = rsYs1;
		this.rsYs2 = rsYs2;
		this.rsYs3 = rsYs3;
		this.rsYs4 = rsYs4;
		this.rsYs5 = rsYs5;
		this.rsNj1 = rsNj1;
		this.rsNj2 = rsNj2;
		this.rsNj3 = rsNj3;
		this.rsNj4 = rsNj4;
		this.rsNj5 = rsNj5;
		this.rsLiss1 = rsLiss1;
		this.rsLiss2 = rsLiss2;
		this.rsLiss3 = rsLiss3;
		this.rsDa = rsDa;
		this.ylRs = ylRs;
		this.ylRsA = ylRsA;
		this.ylRsB = ylRsB;
		this.ylRsOther = ylRsOther;
		this.ylRsOtherVal = ylRsOtherVal;
		this.sfRs = sfRs;
		this.sfRsA = sfRsA;
		this.sfRsB = sfRsB;
		this.sfRsOther = sfRsOther;
		this.sfRsOtherVal = sfRsOtherVal;
		this.aboId = aboId;
		this.effect = effect;
		this.result1 = result1;
		this.result2 = result2;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
		this.checkDate = checkDate;
		this.editRemark = editRemark;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public int getBillId()
	{
		return this.billId;
	}

	public void setBillId(int billId)
	{
		this.billId = billId;
	}

	public String getBillNo()
	{
		return this.billNo;
	}

	public void setBillNo(String billNo)
	{
		this.billNo = billNo;
	}

	public Date getOperDate()
	{
		return this.operDate;
	}

	public void setOperDate(Date operDate)
	{
		this.operDate = operDate;
	}

	public Integer getTemplateId()
	{
		return this.templateId;
	}

	public void setTemplateId(Integer templateId)
	{
		this.templateId = templateId;
	}

	public String getOperName()
	{
		return this.operName;
	}

	public void setOperName(String operName)
	{
		this.operName = operName;
	}

	public String getCheckName()
	{
		return this.checkName;
	}

	public void setCheckName(String checkName)
	{
		this.checkName = checkName;
	}

	public String getBloodType()
	{
		return this.bloodType;
	}

	public void setBloodType(String bloodType)
	{
		this.bloodType = bloodType;
	}

	public String getRhdRes()
	{
		return this.rhdRes;
	}

	public void setRhdRes(String rhdRes)
	{
		this.rhdRes = rhdRes;
	}

	public String getPhenotype()
	{
		return this.phenotype;
	}

	public void setPhenotype(String phenotype)
	{
		this.phenotype = phenotype;
	}

	public String getBloodTypeM()
	{
		return this.bloodTypeM;
	}

	public void setBloodTypeM(String bloodTypeM)
	{
		this.bloodTypeM = bloodTypeM;
	}

	public String getRhdResM()
	{
		return this.rhdResM;
	}

	public void setRhdResM(String rhdResM)
	{
		this.rhdResM = rhdResM;
	}

	public String getPhenotypeM()
	{
		return this.phenotypeM;
	}

	public void setPhenotypeM(String phenotypeM)
	{
		this.phenotypeM = phenotypeM;
	}

	public String getBloodTypeF()
	{
		return this.bloodTypeF;
	}

	public void setBloodTypeF(String bloodTypeF)
	{
		this.bloodTypeF = bloodTypeF;
	}

	public String getRhdResF()
	{
		return this.rhdResF;
	}

	public void setRhdResF(String rhdResF)
	{
		this.rhdResF = rhdResF;
	}

	public String getPhenotypeF()
	{
		return this.phenotypeF;
	}

	public void setPhenotypeF(String phenotypeF)
	{
		this.phenotypeF = phenotypeF;
	}

	public String getRsYs1()
	{
		return this.rsYs1;
	}

	public void setRsYs1(String rsYs1)
	{
		this.rsYs1 = rsYs1;
	}

	public String getRsYs2()
	{
		return this.rsYs2;
	}

	public void setRsYs2(String rsYs2)
	{
		this.rsYs2 = rsYs2;
	}

	public String getRsYs3()
	{
		return this.rsYs3;
	}

	public void setRsYs3(String rsYs3)
	{
		this.rsYs3 = rsYs3;
	}

	public String getRsYs4()
	{
		return this.rsYs4;
	}

	public void setRsYs4(String rsYs4)
	{
		this.rsYs4 = rsYs4;
	}

	public String getRsYs5()
	{
		return this.rsYs5;
	}

	public void setRsYs5(String rsYs5)
	{
		this.rsYs5 = rsYs5;
	}

	public String getRsNj1()
	{
		return this.rsNj1;
	}

	public void setRsNj1(String rsNj1)
	{
		this.rsNj1 = rsNj1;
	}

	public String getRsNj2()
	{
		return this.rsNj2;
	}

	public void setRsNj2(String rsNj2)
	{
		this.rsNj2 = rsNj2;
	}

	public String getRsNj3()
	{
		return this.rsNj3;
	}

	public void setRsNj3(String rsNj3)
	{
		this.rsNj3 = rsNj3;
	}

	public String getRsNj4()
	{
		return this.rsNj4;
	}

	public void setRsNj4(String rsNj4)
	{
		this.rsNj4 = rsNj4;
	}

	public String getRsNj5()
	{
		return this.rsNj5;
	}

	public void setRsNj5(String rsNj5)
	{
		this.rsNj5 = rsNj5;
	}

	public String getRsLiss1()
	{
		return this.rsLiss1;
	}

	public void setRsLiss1(String rsLiss1)
	{
		this.rsLiss1 = rsLiss1;
	}

	public String getRsLiss2()
	{
		return this.rsLiss2;
	}

	public void setRsLiss2(String rsLiss2)
	{
		this.rsLiss2 = rsLiss2;
	}

	public String getRsLiss3()
	{
		return this.rsLiss3;
	}

	public void setRsLiss3(String rsLiss3)
	{
		this.rsLiss3 = rsLiss3;
	}

	public String getRsDa()
	{
		return this.rsDa;
	}

	public void setRsDa(String rsDa)
	{
		this.rsDa = rsDa;
	}

	public Character getYlRs()
	{
		return this.ylRs;
	}

	public void setYlRs(Character ylRs)
	{
		this.ylRs = ylRs;
	}

	public Character getYlRsA()
	{
		return this.ylRsA;
	}

	public void setYlRsA(Character ylRsA)
	{
		this.ylRsA = ylRsA;
	}

	public Character getYlRsB()
	{
		return this.ylRsB;
	}

	public void setYlRsB(Character ylRsB)
	{
		this.ylRsB = ylRsB;
	}

	public Character getYlRsOther()
	{
		return this.ylRsOther;
	}

	public void setYlRsOther(Character ylRsOther)
	{
		this.ylRsOther = ylRsOther;
	}

	public String getYlRsOtherVal()
	{
		return this.ylRsOtherVal;
	}

	public void setYlRsOtherVal(String ylRsOtherVal)
	{
		this.ylRsOtherVal = ylRsOtherVal;
	}

	public Character getSfRs()
	{
		return this.sfRs;
	}

	public void setSfRs(Character sfRs)
	{
		this.sfRs = sfRs;
	}

	public Character getSfRsA()
	{
		return this.sfRsA;
	}

	public void setSfRsA(Character sfRsA)
	{
		this.sfRsA = sfRsA;
	}

	public Character getSfRsB()
	{
		return this.sfRsB;
	}

	public void setSfRsB(Character sfRsB)
	{
		this.sfRsB = sfRsB;
	}

	public Character getSfRsOther()
	{
		return this.sfRsOther;
	}

	public void setSfRsOther(Character sfRsOther)
	{
		this.sfRsOther = sfRsOther;
	}

	public String getSfRsOtherVal()
	{
		return this.sfRsOtherVal;
	}

	public void setSfRsOtherVal(String sfRsOtherVal)
	{
		this.sfRsOtherVal = sfRsOtherVal;
	}

	public Character getAboId()
	{
		return this.aboId;
	}

	public void setAboId(Character aboId)
	{
		this.aboId = aboId;
	}

	public String getEffect()
	{
		return this.effect;
	}

	public void setEffect(String effect)
	{
		this.effect = effect;
	}

	public String getResult1()
	{
		return this.result1;
	}

	public void setResult1(String result1)
	{
		this.result1 = result1;
	}

	public String getResult2()
	{
		return this.result2;
	}

	public void setResult2(String result2)
	{
		this.result2 = result2;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public Date getCheckDate()
	{
		return this.checkDate;
	}

	public void setCheckDate(Date checkDate)
	{
		this.checkDate = checkDate;
	}

	public String getEditRemark()
	{
		return this.editRemark;
	}

	public void setEditRemark(String editRemark)
	{
		this.editRemark = editRemark;
	}

}
