package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * CImgtDetailT generated by hbm2java
 */
public class CImgtDetailT implements java.io.Serializable
{

	private CImgtDetailTId id;

	public CImgtDetailT()
	{
	}

	public CImgtDetailT(CImgtDetailTId id)
	{
		this.id = id;
	}

	public CImgtDetailTId getId()
	{
		return this.id;
	}

	public void setId(CImgtDetailTId id)
	{
		this.id = id;
	}

}
