package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * CInvoiceRecordTId generated by hbm2java
 */
public class CInvoiceRecordTId implements java.io.Serializable
{

	private int id;
	private Integer billId;
	private String billNo;
	private String invoiceNo;
	private String invoiceFee;
	private String hospitalName;
	private Character feeType;
	private String useFlag;
	private String feeItem;
	private String remark;
	private Date recordTime;
	private String recordName;
	private String patientName;

	public CInvoiceRecordTId()
	{
	}

	public CInvoiceRecordTId(int id, String billNo)
	{
		this.id = id;
		this.billNo = billNo;
	}

	public CInvoiceRecordTId(int id, Integer billId, String billNo, String invoiceNo, String invoiceFee,
			String hospitalName, Character feeType, String useFlag, String feeItem, String remark, Date recordTime,
			String recordName, String patientName)
	{
		this.id = id;
		this.billId = billId;
		this.billNo = billNo;
		this.invoiceNo = invoiceNo;
		this.invoiceFee = invoiceFee;
		this.hospitalName = hospitalName;
		this.feeType = feeType;
		this.useFlag = useFlag;
		this.feeItem = feeItem;
		this.remark = remark;
		this.recordTime = recordTime;
		this.recordName = recordName;
		this.patientName = patientName;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Integer getBillId()
	{
		return this.billId;
	}

	public void setBillId(Integer billId)
	{
		this.billId = billId;
	}

	public String getBillNo()
	{
		return this.billNo;
	}

	public void setBillNo(String billNo)
	{
		this.billNo = billNo;
	}

	public String getInvoiceNo()
	{
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo)
	{
		this.invoiceNo = invoiceNo;
	}

	public String getInvoiceFee()
	{
		return this.invoiceFee;
	}

	public void setInvoiceFee(String invoiceFee)
	{
		this.invoiceFee = invoiceFee;
	}

	public String getHospitalName()
	{
		return this.hospitalName;
	}

	public void setHospitalName(String hospitalName)
	{
		this.hospitalName = hospitalName;
	}

	public Character getFeeType()
	{
		return this.feeType;
	}

	public void setFeeType(Character feeType)
	{
		this.feeType = feeType;
	}

	public String getUseFlag()
	{
		return this.useFlag;
	}

	public void setUseFlag(String useFlag)
	{
		this.useFlag = useFlag;
	}

	public String getFeeItem()
	{
		return this.feeItem;
	}

	public void setFeeItem(String feeItem)
	{
		this.feeItem = feeItem;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public String getPatientName()
	{
		return this.patientName;
	}

	public void setPatientName(String patientName)
	{
		this.patientName = patientName;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CInvoiceRecordTId))
			return false;
		CInvoiceRecordTId castOther = (CInvoiceRecordTId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getBillId() == castOther.getBillId()) || (this.getBillId() != null
						&& castOther.getBillId() != null && this.getBillId().equals(castOther.getBillId())))
				&& ((this.getBillNo() == castOther.getBillNo()) || (this.getBillNo() != null
						&& castOther.getBillNo() != null && this.getBillNo().equals(castOther.getBillNo())))
				&& ((this.getInvoiceNo() == castOther.getInvoiceNo()) || (this.getInvoiceNo() != null
						&& castOther.getInvoiceNo() != null && this.getInvoiceNo().equals(castOther.getInvoiceNo())))
				&& ((this.getInvoiceFee() == castOther.getInvoiceFee()) || (this.getInvoiceFee() != null
						&& castOther.getInvoiceFee() != null && this.getInvoiceFee().equals(castOther.getInvoiceFee())))
				&& ((this.getHospitalName() == castOther.getHospitalName())
						|| (this.getHospitalName() != null && castOther.getHospitalName() != null
								&& this.getHospitalName().equals(castOther.getHospitalName())))
				&& ((this.getFeeType() == castOther.getFeeType()) || (this.getFeeType() != null
						&& castOther.getFeeType() != null && this.getFeeType().equals(castOther.getFeeType())))
				&& ((this.getUseFlag() == castOther.getUseFlag()) || (this.getUseFlag() != null
						&& castOther.getUseFlag() != null && this.getUseFlag().equals(castOther.getUseFlag())))
				&& ((this.getFeeItem() == castOther.getFeeItem()) || (this.getFeeItem() != null
						&& castOther.getFeeItem() != null && this.getFeeItem().equals(castOther.getFeeItem())))
				&& ((this.getRemark() == castOther.getRemark()) || (this.getRemark() != null
						&& castOther.getRemark() != null && this.getRemark().equals(castOther.getRemark())))
				&& ((this.getRecordTime() == castOther.getRecordTime()) || (this.getRecordTime() != null
						&& castOther.getRecordTime() != null && this.getRecordTime().equals(castOther.getRecordTime())))
				&& ((this.getRecordName() == castOther.getRecordName()) || (this.getRecordName() != null
						&& castOther.getRecordName() != null && this.getRecordName().equals(castOther.getRecordName())))
				&& ((this.getPatientName() == castOther.getPatientName())
						|| (this.getPatientName() != null && castOther.getPatientName() != null
								&& this.getPatientName().equals(castOther.getPatientName())));
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getBillId() == null ? 0 : this.getBillId().hashCode());
		result = 37 * result + (getBillNo() == null ? 0 : this.getBillNo().hashCode());
		result = 37 * result + (getInvoiceNo() == null ? 0 : this.getInvoiceNo().hashCode());
		result = 37 * result + (getInvoiceFee() == null ? 0 : this.getInvoiceFee().hashCode());
		result = 37 * result + (getHospitalName() == null ? 0 : this.getHospitalName().hashCode());
		result = 37 * result + (getFeeType() == null ? 0 : this.getFeeType().hashCode());
		result = 37 * result + (getUseFlag() == null ? 0 : this.getUseFlag().hashCode());
		result = 37 * result + (getFeeItem() == null ? 0 : this.getFeeItem().hashCode());
		result = 37 * result + (getRemark() == null ? 0 : this.getRemark().hashCode());
		result = 37 * result + (getRecordTime() == null ? 0 : this.getRecordTime().hashCode());
		result = 37 * result + (getRecordName() == null ? 0 : this.getRecordName().hashCode());
		result = 37 * result + (getPatientName() == null ? 0 : this.getPatientName().hashCode());
		return result;
	}

}
