package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * CRuleAlleleDetailT generated by hbm2java
 */
public class CRuleAlleleDetailT implements java.io.Serializable
{

	private CRuleAlleleDetailTId id;

	public CRuleAlleleDetailT()
	{
	}

	public CRuleAlleleDetailT(CRuleAlleleDetailTId id)
	{
		this.id = id;
	}

	public CRuleAlleleDetailTId getId()
	{
		return this.id;
	}

	public void setId(CRuleAlleleDetailTId id)
	{
		this.id = id;
	}

}
