package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * CRuleResourceDetailT generated by hbm2java
 */
public class CRuleResourceDetailT implements java.io.Serializable
{

	private CRuleResourceDetailTId id;

	public CRuleResourceDetailT()
	{
	}

	public CRuleResourceDetailT(CRuleResourceDetailTId id)
	{
		this.id = id;
	}

	public CRuleResourceDetailTId getId()
	{
		return this.id;
	}

	public void setId(CRuleResourceDetailTId id)
	{
		this.id = id;
	}

}
