package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * CRuleCwdT generated by hbm2java
 */
public class CRuleCwdT implements java.io.Serializable
{

	private CRuleCwdTId id;

	public CRuleCwdT()
	{
	}

	public CRuleCwdT(CRuleCwdTId id)
	{
		this.id = id;
	}

	public CRuleCwdTId getId()
	{
		return this.id;
	}

	public void setId(CRuleCwdTId id)
	{
		this.id = id;
	}

}
