package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * CRuleAmbiguityT generated by hbm2java
 */
public class CRuleAmbiguityT implements java.io.Serializable
{

	private CRuleAmbiguityTId id;

	public CRuleAmbiguityT()
	{
	}

	public CRuleAmbiguityT(CRuleAmbiguityTId id)
	{
		this.id = id;
	}

	public CRuleAmbiguityTId getId()
	{
		return this.id;
	}

	public void setId(CRuleAmbiguityTId id)
	{
		this.id = id;
	}

}
