package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * CRuleAmbiguityDetailT generated by hbm2java
 */
public class CRuleAmbiguityDetailT implements java.io.Serializable
{

	private CRuleAmbiguityDetailTId id;

	public CRuleAmbiguityDetailT()
	{
	}

	public CRuleAmbiguityDetailT(CRuleAmbiguityDetailTId id)
	{
		this.id = id;
	}

	public CRuleAmbiguityDetailTId getId()
	{
		return this.id;
	}

	public void setId(CRuleAmbiguityDetailTId id)
	{
		this.id = id;
	}

}
