package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * HlaConcentration generated by hbm2java
 */
public class HlaConcentration implements java.io.Serializable
{

	private int id;
	private String boardNo;
	private String code;
	private Integer no;
	private String barcode;
	private BigDecimal oldCt;
	private BigDecimal purity;
	private Character method;
	private String remark;
	private Date recordTime;
	private String recordName;

	public HlaConcentration()
	{
	}

	public HlaConcentration(int id, String barcode)
	{
		this.id = id;
		this.barcode = barcode;
	}

	public HlaConcentration(int id, String boardNo, String code, Integer no, String barcode, BigDecimal oldCt,
			BigDecimal purity, Character method, String remark, Date recordTime, String recordName)
	{
		this.id = id;
		this.boardNo = boardNo;
		this.code = code;
		this.no = no;
		this.barcode = barcode;
		this.oldCt = oldCt;
		this.purity = purity;
		this.method = method;
		this.remark = remark;
		this.recordTime = recordTime;
		this.recordName = recordName;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getBoardNo()
	{
		return this.boardNo;
	}

	public void setBoardNo(String boardNo)
	{
		this.boardNo = boardNo;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public Integer getNo()
	{
		return this.no;
	}

	public void setNo(Integer no)
	{
		this.no = no;
	}

	public String getBarcode()
	{
		return this.barcode;
	}

	public void setBarcode(String barcode)
	{
		this.barcode = barcode;
	}

	public BigDecimal getOldCt()
	{
		return this.oldCt;
	}

	public void setOldCt(BigDecimal oldCt)
	{
		this.oldCt = oldCt;
	}

	public BigDecimal getPurity()
	{
		return this.purity;
	}

	public void setPurity(BigDecimal purity)
	{
		this.purity = purity;
	}

	public Character getMethod()
	{
		return this.method;
	}

	public void setMethod(Character method)
	{
		this.method = method;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

}
