package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * HlaReportResult generated by hbm2java
 */
public class HlaReportResult implements java.io.Serializable
{

	private int id;
	private String sampleNo;
	private String resultDq;
	private String resultA;
	private String resultB;
	private String resultC;
	private String resultDr;
	private String remark;
	private String recordName;
	private Date recordTime;
	private Integer billId;

	public HlaReportResult()
	{
	}

	public HlaReportResult(int id, String sampleNo)
	{
		this.id = id;
		this.sampleNo = sampleNo;
	}

	public HlaReportResult(int id, String sampleNo, String resultDq, String resultA, String resultB, String resultC,
			String resultDr, String remark, String recordName, Date recordTime, Integer billId)
	{
		this.id = id;
		this.sampleNo = sampleNo;
		this.resultDq = resultDq;
		this.resultA = resultA;
		this.resultB = resultB;
		this.resultC = resultC;
		this.resultDr = resultDr;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
		this.billId = billId;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getSampleNo()
	{
		return this.sampleNo;
	}

	public void setSampleNo(String sampleNo)
	{
		this.sampleNo = sampleNo;
	}

	public String getResultDq()
	{
		return this.resultDq;
	}

	public void setResultDq(String resultDq)
	{
		this.resultDq = resultDq;
	}

	public String getResultA()
	{
		return this.resultA;
	}

	public void setResultA(String resultA)
	{
		this.resultA = resultA;
	}

	public String getResultB()
	{
		return this.resultB;
	}

	public void setResultB(String resultB)
	{
		this.resultB = resultB;
	}

	public String getResultC()
	{
		return this.resultC;
	}

	public void setResultC(String resultC)
	{
		this.resultC = resultC;
	}

	public String getResultDr()
	{
		return this.resultDr;
	}

	public void setResultDr(String resultDr)
	{
		this.resultDr = resultDr;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public Integer getBillId()
	{
		return this.billId;
	}

	public void setBillId(Integer billId)
	{
		this.billId = billId;
	}

}
