package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * HlaSbt generated by hbm2java
 */
public class HlaSbt implements java.io.Serializable
{

	private HlaSbtId id;

	public HlaSbt()
	{
	}

	public HlaSbt(HlaSbtId id)
	{
		this.id = id;
	}

	public HlaSbtId getId()
	{
		return this.id;
	}

	public void setId(HlaSbtId id)
	{
		this.id = id;
	}

}
