package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * LabEnv generated by hbm2java
 */
public class LabEnv implements java.io.Serializable
{

	private int id;
	private Date envDate;
	private char envId;
	private String reason;
	private String remark;
	private String recordName;
	private Date recordTime;

	public LabEnv()
	{
	}

	public LabEnv(int id, Date envDate, char envId)
	{
		this.id = id;
		this.envDate = envDate;
		this.envId = envId;
	}

	public LabEnv(int id, Date envDate, char envId, String reason, String remark, String recordName, Date recordTime)
	{
		this.id = id;
		this.envDate = envDate;
		this.envId = envId;
		this.reason = reason;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Date getEnvDate()
	{
		return this.envDate;
	}

	public void setEnvDate(Date envDate)
	{
		this.envDate = envDate;
	}

	public char getEnvId()
	{
		return this.envId;
	}

	public void setEnvId(char envId)
	{
		this.envId = envId;
	}

	public String getReason()
	{
		return this.reason;
	}

	public void setReason(String reason)
	{
		this.reason = reason;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

}
