package riswell.model;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * MatchBill generated by hbm2java
 */
@Entity
public class MatchBill implements java.io.Serializable
{

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int id;
	private String billNo;
	private char billKind;
	private Integer hospitalId;
	private String hospitalName;
	private String reqDoctor;
	private Date reqDate;
	private String name;
	private String seqNo;
	private Character sex;
	private Integer age;
	private BigDecimal weight;
	private String telphone;
	private String mobile;
	private String fax;
	private String post;
	private String address;
	private String nation;
	private String diagnose;
	private BigDecimal wbNum;
	private Date acceptDate;
	private String acceptMan;
	private Character reportType;
	private Date reportDate;
	private char feeId;
	private char labId;
	private char whId;
	private Character gpId;
	private String providerNo;
	private Character firstId;
	private String preResult;
	private String firstNo;
	private String disease;
	private String patientAbo;
	private String providerAbo;
	private Character transKind;
	private Character providerFrom;
	private Date transDate;
	private Integer transDays;
	private Integer transNum;
	private char rejectId;
	private String rejectReason;
	private String rejectDeal;
	private String status;
	private String billName;
	private String checkMan;
	private Date checkDate;
	private String repOper;
	private String repCheck;
	private String repRes;
	private Date repDate;
	private String remark;
	private Date recordTime;
	private String recordName;
	private Character reportNumber;
	private String reagent1;
	private String reagent2;
	private String reportNo;
	private String hositalNo;
	private String invoiceNo;
	private String invoiceType;
	private String datebirth;
	private String diagnosis;
	private String email;
	private String company;
	private Date chushengriqi;
	private String linchuangzhengduan;
	private Character menzhen;
	private Character zhuyuan;
	private String chuanghao;
	private String zhuyuanhao;
	private Date jiancedanriqi;
	private String binganhao;
	private String remark1;
	private String remark2;
	private String remark3;
	private String remark4;
	private String remark5;
	private String fenxi;
	private String zhushi;
	private String shenfenzhenghao;
	@OneToMany(mappedBy="matchBill")
	private Set<SampleInfo> sampleInfos = new HashSet<SampleInfo>(0);

	public MatchBill()
	{
	}

	public MatchBill(int id, String billNo, char billKind, char feeId, char labId, char whId, char rejectId)
	{
		this.id = id;
		this.billNo = billNo;
		this.billKind = billKind;
		this.feeId = feeId;
		this.labId = labId;
		this.whId = whId;
		this.rejectId = rejectId;
	}

	public MatchBill(int id, String billNo, char billKind, Integer hospitalId, String hospitalName, String reqDoctor,
			Date reqDate, String name, String seqNo, Character sex, Integer age, BigDecimal weight, String telphone,
			String mobile, String fax, String post, String address, String nation, String diagnose, BigDecimal wbNum,
			Date acceptDate, String acceptMan, Character reportType, Date reportDate, char feeId, char labId, char whId,
			Character gpId, String providerNo, Character firstId, String preResult, String firstNo, String disease,
			String patientAbo, String providerAbo, Character transKind, Character providerFrom, Date transDate,
			Integer transDays, Integer transNum, char rejectId, String rejectReason, String rejectDeal, String status,
			String billName, String checkMan, Date checkDate, String repOper, String repCheck, String repRes,
			Date repDate, String remark, Date recordTime, String recordName, Character reportNumber, String reagent1,
			String reagent2, String reportNo, String hositalNo, String invoiceNo, String invoiceType, String datebirth,
			String diagnosis, String email, String company, Date chushengriqi, String linchuangzhengduan,
			Character menzhen, Character zhuyuan, String chuanghao, String zhuyuanhao, Date jiancedanriqi,
			String binganhao, String remark1, String remark2, String remark3, String remark4, String remark5,
			String fenxi, String zhushi, String shenfenzhenghao, Set<SampleInfo> sampleInfos)
	{
		this.id = id;
		this.billNo = billNo;
		this.billKind = billKind;
		this.hospitalId = hospitalId;
		this.hospitalName = hospitalName;
		this.reqDoctor = reqDoctor;
		this.reqDate = reqDate;
		this.name = name;
		this.seqNo = seqNo;
		this.sex = sex;
		this.age = age;
		this.weight = weight;
		this.telphone = telphone;
		this.mobile = mobile;
		this.fax = fax;
		this.post = post;
		this.address = address;
		this.nation = nation;
		this.diagnose = diagnose;
		this.wbNum = wbNum;
		this.acceptDate = acceptDate;
		this.acceptMan = acceptMan;
		this.reportType = reportType;
		this.reportDate = reportDate;
		this.feeId = feeId;
		this.labId = labId;
		this.whId = whId;
		this.gpId = gpId;
		this.providerNo = providerNo;
		this.firstId = firstId;
		this.preResult = preResult;
		this.firstNo = firstNo;
		this.disease = disease;
		this.patientAbo = patientAbo;
		this.providerAbo = providerAbo;
		this.transKind = transKind;
		this.providerFrom = providerFrom;
		this.transDate = transDate;
		this.transDays = transDays;
		this.transNum = transNum;
		this.rejectId = rejectId;
		this.rejectReason = rejectReason;
		this.rejectDeal = rejectDeal;
		this.status = status;
		this.billName = billName;
		this.checkMan = checkMan;
		this.checkDate = checkDate;
		this.repOper = repOper;
		this.repCheck = repCheck;
		this.repRes = repRes;
		this.repDate = repDate;
		this.remark = remark;
		this.recordTime = recordTime;
		this.recordName = recordName;
		this.reportNumber = reportNumber;
		this.reagent1 = reagent1;
		this.reagent2 = reagent2;
		this.reportNo = reportNo;
		this.hositalNo = hositalNo;
		this.invoiceNo = invoiceNo;
		this.invoiceType = invoiceType;
		this.datebirth = datebirth;
		this.diagnosis = diagnosis;
		this.email = email;
		this.company = company;
		this.chushengriqi = chushengriqi;
		this.linchuangzhengduan = linchuangzhengduan;
		this.menzhen = menzhen;
		this.zhuyuan = zhuyuan;
		this.chuanghao = chuanghao;
		this.zhuyuanhao = zhuyuanhao;
		this.jiancedanriqi = jiancedanriqi;
		this.binganhao = binganhao;
		this.remark1 = remark1;
		this.remark2 = remark2;
		this.remark3 = remark3;
		this.remark4 = remark4;
		this.remark5 = remark5;
		this.fenxi = fenxi;
		this.zhushi = zhushi;
		this.shenfenzhenghao = shenfenzhenghao;
		this.sampleInfos = sampleInfos;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getBillNo()
	{
		return this.billNo;
	}

	public void setBillNo(String billNo)
	{
		this.billNo = billNo;
	}

	public char getBillKind()
	{
		return this.billKind;
	}

	public void setBillKind(char billKind)
	{
		this.billKind = billKind;
	}

	public Integer getHospitalId()
	{
		return this.hospitalId;
	}

	public void setHospitalId(Integer hospitalId)
	{
		this.hospitalId = hospitalId;
	}

	public String getHospitalName()
	{
		return this.hospitalName;
	}

	public void setHospitalName(String hospitalName)
	{
		this.hospitalName = hospitalName;
	}

	public String getReqDoctor()
	{
		return this.reqDoctor;
	}

	public void setReqDoctor(String reqDoctor)
	{
		this.reqDoctor = reqDoctor;
	}

	public Date getReqDate()
	{
		return this.reqDate;
	}

	public void setReqDate(Date reqDate)
	{
		this.reqDate = reqDate;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getSeqNo()
	{
		return this.seqNo;
	}

	public void setSeqNo(String seqNo)
	{
		this.seqNo = seqNo;
	}

	public Character getSex()
	{
		return this.sex;
	}

	public void setSex(Character sex)
	{
		this.sex = sex;
	}

	public Integer getAge()
	{
		return this.age;
	}

	public void setAge(Integer age)
	{
		this.age = age;
	}

	public BigDecimal getWeight()
	{
		return this.weight;
	}

	public void setWeight(BigDecimal weight)
	{
		this.weight = weight;
	}

	public String getTelphone()
	{
		return this.telphone;
	}

	public void setTelphone(String telphone)
	{
		this.telphone = telphone;
	}

	public String getMobile()
	{
		return this.mobile;
	}

	public void setMobile(String mobile)
	{
		this.mobile = mobile;
	}

	public String getFax()
	{
		return this.fax;
	}

	public void setFax(String fax)
	{
		this.fax = fax;
	}

	public String getPost()
	{
		return this.post;
	}

	public void setPost(String post)
	{
		this.post = post;
	}

	public String getAddress()
	{
		return this.address;
	}

	public void setAddress(String address)
	{
		this.address = address;
	}

	public String getNation()
	{
		return this.nation;
	}

	public void setNation(String nation)
	{
		this.nation = nation;
	}

	public String getDiagnose()
	{
		return this.diagnose;
	}

	public void setDiagnose(String diagnose)
	{
		this.diagnose = diagnose;
	}

	public BigDecimal getWbNum()
	{
		return this.wbNum;
	}

	public void setWbNum(BigDecimal wbNum)
	{
		this.wbNum = wbNum;
	}

	public Date getAcceptDate()
	{
		return this.acceptDate;
	}

	public void setAcceptDate(Date acceptDate)
	{
		this.acceptDate = acceptDate;
	}

	public String getAcceptMan()
	{
		return this.acceptMan;
	}

	public void setAcceptMan(String acceptMan)
	{
		this.acceptMan = acceptMan;
	}

	public Character getReportType()
	{
		return this.reportType;
	}

	public void setReportType(Character reportType)
	{
		this.reportType = reportType;
	}

	public Date getReportDate()
	{
		return this.reportDate;
	}

	public void setReportDate(Date reportDate)
	{
		this.reportDate = reportDate;
	}

	public char getFeeId()
	{
		return this.feeId;
	}

	public void setFeeId(char feeId)
	{
		this.feeId = feeId;
	}

	public char getLabId()
	{
		return this.labId;
	}

	public void setLabId(char labId)
	{
		this.labId = labId;
	}

	public char getWhId()
	{
		return this.whId;
	}

	public void setWhId(char whId)
	{
		this.whId = whId;
	}

	public Character getGpId()
	{
		return this.gpId;
	}

	public void setGpId(Character gpId)
	{
		this.gpId = gpId;
	}

	public String getProviderNo()
	{
		return this.providerNo;
	}

	public void setProviderNo(String providerNo)
	{
		this.providerNo = providerNo;
	}

	public Character getFirstId()
	{
		return this.firstId;
	}

	public void setFirstId(Character firstId)
	{
		this.firstId = firstId;
	}

	public String getPreResult()
	{
		return this.preResult;
	}

	public void setPreResult(String preResult)
	{
		this.preResult = preResult;
	}

	public String getFirstNo()
	{
		return this.firstNo;
	}

	public void setFirstNo(String firstNo)
	{
		this.firstNo = firstNo;
	}

	public String getDisease()
	{
		return this.disease;
	}

	public void setDisease(String disease)
	{
		this.disease = disease;
	}

	public String getPatientAbo()
	{
		return this.patientAbo;
	}

	public void setPatientAbo(String patientAbo)
	{
		this.patientAbo = patientAbo;
	}

	public String getProviderAbo()
	{
		return this.providerAbo;
	}

	public void setProviderAbo(String providerAbo)
	{
		this.providerAbo = providerAbo;
	}

	public Character getTransKind()
	{
		return this.transKind;
	}

	public void setTransKind(Character transKind)
	{
		this.transKind = transKind;
	}

	public Character getProviderFrom()
	{
		return this.providerFrom;
	}

	public void setProviderFrom(Character providerFrom)
	{
		this.providerFrom = providerFrom;
	}

	public Date getTransDate()
	{
		return this.transDate;
	}

	public void setTransDate(Date transDate)
	{
		this.transDate = transDate;
	}

	public Integer getTransDays()
	{
		return this.transDays;
	}

	public void setTransDays(Integer transDays)
	{
		this.transDays = transDays;
	}

	public Integer getTransNum()
	{
		return this.transNum;
	}

	public void setTransNum(Integer transNum)
	{
		this.transNum = transNum;
	}

	public char getRejectId()
	{
		return this.rejectId;
	}

	public void setRejectId(char rejectId)
	{
		this.rejectId = rejectId;
	}

	public String getRejectReason()
	{
		return this.rejectReason;
	}

	public void setRejectReason(String rejectReason)
	{
		this.rejectReason = rejectReason;
	}

	public String getRejectDeal()
	{
		return this.rejectDeal;
	}

	public void setRejectDeal(String rejectDeal)
	{
		this.rejectDeal = rejectDeal;
	}

	public String getStatus()
	{
		return this.status;
	}

	public void setStatus(String status)
	{
		this.status = status;
	}

	public String getBillName()
	{
		return this.billName;
	}

	public void setBillName(String billName)
	{
		this.billName = billName;
	}

	public String getCheckMan()
	{
		return this.checkMan;
	}

	public void setCheckMan(String checkMan)
	{
		this.checkMan = checkMan;
	}

	public Date getCheckDate()
	{
		return this.checkDate;
	}

	public void setCheckDate(Date checkDate)
	{
		this.checkDate = checkDate;
	}

	public String getRepOper()
	{
		return this.repOper;
	}

	public void setRepOper(String repOper)
	{
		this.repOper = repOper;
	}

	public String getRepCheck()
	{
		return this.repCheck;
	}

	public void setRepCheck(String repCheck)
	{
		this.repCheck = repCheck;
	}

	public String getRepRes()
	{
		return this.repRes;
	}

	public void setRepRes(String repRes)
	{
		this.repRes = repRes;
	}

	public Date getRepDate()
	{
		return this.repDate;
	}

	public void setRepDate(Date repDate)
	{
		this.repDate = repDate;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Character getReportNumber()
	{
		return this.reportNumber;
	}

	public void setReportNumber(Character reportNumber)
	{
		this.reportNumber = reportNumber;
	}

	public String getReagent1()
	{
		return this.reagent1;
	}

	public void setReagent1(String reagent1)
	{
		this.reagent1 = reagent1;
	}

	public String getReagent2()
	{
		return this.reagent2;
	}

	public void setReagent2(String reagent2)
	{
		this.reagent2 = reagent2;
	}

	public String getReportNo()
	{
		return this.reportNo;
	}

	public void setReportNo(String reportNo)
	{
		this.reportNo = reportNo;
	}

	public String getHositalNo()
	{
		return this.hositalNo;
	}

	public void setHositalNo(String hositalNo)
	{
		this.hositalNo = hositalNo;
	}

	public String getInvoiceNo()
	{
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo)
	{
		this.invoiceNo = invoiceNo;
	}

	public String getInvoiceType()
	{
		return this.invoiceType;
	}

	public void setInvoiceType(String invoiceType)
	{
		this.invoiceType = invoiceType;
	}

	public String getDatebirth()
	{
		return this.datebirth;
	}

	public void setDatebirth(String datebirth)
	{
		this.datebirth = datebirth;
	}

	public String getDiagnosis()
	{
		return this.diagnosis;
	}

	public void setDiagnosis(String diagnosis)
	{
		this.diagnosis = diagnosis;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public String getCompany()
	{
		return this.company;
	}

	public void setCompany(String company)
	{
		this.company = company;
	}

	public Date getChushengriqi()
	{
		return this.chushengriqi;
	}

	public void setChushengriqi(Date chushengriqi)
	{
		this.chushengriqi = chushengriqi;
	}

	public String getLinchuangzhengduan()
	{
		return this.linchuangzhengduan;
	}

	public void setLinchuangzhengduan(String linchuangzhengduan)
	{
		this.linchuangzhengduan = linchuangzhengduan;
	}

	public Character getMenzhen()
	{
		return this.menzhen;
	}

	public void setMenzhen(Character menzhen)
	{
		this.menzhen = menzhen;
	}

	public Character getZhuyuan()
	{
		return this.zhuyuan;
	}

	public void setZhuyuan(Character zhuyuan)
	{
		this.zhuyuan = zhuyuan;
	}

	public String getChuanghao()
	{
		return this.chuanghao;
	}

	public void setChuanghao(String chuanghao)
	{
		this.chuanghao = chuanghao;
	}

	public String getZhuyuanhao()
	{
		return this.zhuyuanhao;
	}

	public void setZhuyuanhao(String zhuyuanhao)
	{
		this.zhuyuanhao = zhuyuanhao;
	}

	public Date getJiancedanriqi()
	{
		return this.jiancedanriqi;
	}

	public void setJiancedanriqi(Date jiancedanriqi)
	{
		this.jiancedanriqi = jiancedanriqi;
	}

	public String getBinganhao()
	{
		return this.binganhao;
	}

	public void setBinganhao(String binganhao)
	{
		this.binganhao = binganhao;
	}

	public String getRemark1()
	{
		return this.remark1;
	}

	public void setRemark1(String remark1)
	{
		this.remark1 = remark1;
	}

	public String getRemark2()
	{
		return this.remark2;
	}

	public void setRemark2(String remark2)
	{
		this.remark2 = remark2;
	}

	public String getRemark3()
	{
		return this.remark3;
	}

	public void setRemark3(String remark3)
	{
		this.remark3 = remark3;
	}

	public String getRemark4()
	{
		return this.remark4;
	}

	public void setRemark4(String remark4)
	{
		this.remark4 = remark4;
	}

	public String getRemark5()
	{
		return this.remark5;
	}

	public void setRemark5(String remark5)
	{
		this.remark5 = remark5;
	}

	public String getFenxi()
	{
		return this.fenxi;
	}

	public void setFenxi(String fenxi)
	{
		this.fenxi = fenxi;
	}

	public String getZhushi()
	{
		return this.zhushi;
	}

	public void setZhushi(String zhushi)
	{
		this.zhushi = zhushi;
	}

	public String getShenfenzhenghao()
	{
		return this.shenfenzhenghao;
	}

	public void setShenfenzhenghao(String shenfenzhenghao)
	{
		this.shenfenzhenghao = shenfenzhenghao;
	}

	public Set<SampleInfo> getSampleInfos()
	{
		return this.sampleInfos;
	}

	public void setSampleInfos(Set<SampleInfo> sampleInfos)
	{
		this.sampleInfos = sampleInfos;
	}

}
