package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * MatchBillFeeRecord generated by hbm2java
 */
public class MatchBillFeeRecord implements java.io.Serializable
{

	private MatchBillFeeRecordId id;

	public MatchBillFeeRecord()
	{
	}

	public MatchBillFeeRecord(MatchBillFeeRecordId id)
	{
		this.id = id;
	}

	public MatchBillFeeRecordId getId()
	{
		return this.id;
	}

	public void setId(MatchBillFeeRecordId id)
	{
		this.id = id;
	}

}
