package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * PbcatvldId generated by hbm2java
 */
public class PbcatvldId implements java.io.Serializable
{

	private String pbvName;
	private String pbvVald;
	private short pbvType;
	private Integer pbvCntr;
	private String pbvMsg;

	public PbcatvldId()
	{
	}

	public PbcatvldId(String pbvName, String pbvVald, short pbvType)
	{
		this.pbvName = pbvName;
		this.pbvVald = pbvVald;
		this.pbvType = pbvType;
	}

	public PbcatvldId(String pbvName, String pbvVald, short pbvType, Integer pbvCntr, String pbvMsg)
	{
		this.pbvName = pbvName;
		this.pbvVald = pbvVald;
		this.pbvType = pbvType;
		this.pbvCntr = pbvCntr;
		this.pbvMsg = pbvMsg;
	}

	public String getPbvName()
	{
		return this.pbvName;
	}

	public void setPbvName(String pbvName)
	{
		this.pbvName = pbvName;
	}

	public String getPbvVald()
	{
		return this.pbvVald;
	}

	public void setPbvVald(String pbvVald)
	{
		this.pbvVald = pbvVald;
	}

	public short getPbvType()
	{
		return this.pbvType;
	}

	public void setPbvType(short pbvType)
	{
		this.pbvType = pbvType;
	}

	public Integer getPbvCntr()
	{
		return this.pbvCntr;
	}

	public void setPbvCntr(Integer pbvCntr)
	{
		this.pbvCntr = pbvCntr;
	}

	public String getPbvMsg()
	{
		return this.pbvMsg;
	}

	public void setPbvMsg(String pbvMsg)
	{
		this.pbvMsg = pbvMsg;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PbcatvldId))
			return false;
		PbcatvldId castOther = (PbcatvldId) other;

		return ((this.getPbvName() == castOther.getPbvName()) || (this.getPbvName() != null
				&& castOther.getPbvName() != null && this.getPbvName().equals(castOther.getPbvName())))
				&& ((this.getPbvVald() == castOther.getPbvVald()) || (this.getPbvVald() != null
						&& castOther.getPbvVald() != null && this.getPbvVald().equals(castOther.getPbvVald())))
				&& (this.getPbvType() == castOther.getPbvType())
				&& ((this.getPbvCntr() == castOther.getPbvCntr()) || (this.getPbvCntr() != null
						&& castOther.getPbvCntr() != null && this.getPbvCntr().equals(castOther.getPbvCntr())))
				&& ((this.getPbvMsg() == castOther.getPbvMsg()) || (this.getPbvMsg() != null
						&& castOther.getPbvMsg() != null && this.getPbvMsg().equals(castOther.getPbvMsg())));
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result + (getPbvName() == null ? 0 : this.getPbvName().hashCode());
		result = 37 * result + (getPbvVald() == null ? 0 : this.getPbvVald().hashCode());
		result = 37 * result + this.getPbvType();
		result = 37 * result + (getPbvCntr() == null ? 0 : this.getPbvCntr().hashCode());
		result = 37 * result + (getPbvMsg() == null ? 0 : this.getPbvMsg().hashCode());
		return result;
	}

}
