package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * Pbcatedt generated by hbm2java
 */
public class Pbcatedt implements java.io.Serializable
{

	private PbcatedtId id;

	public Pbcatedt()
	{
	}

	public Pbcatedt(PbcatedtId id)
	{
		this.id = id;
	}

	public PbcatedtId getId()
	{
		return this.id;
	}

	public void setId(PbcatedtId id)
	{
		this.id = id;
	}

}
