package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * Pbcatvld generated by hbm2java
 */
public class Pbcatvld implements java.io.Serializable
{

	private PbcatvldId id;

	public Pbcatvld()
	{
	}

	public Pbcatvld(PbcatvldId id)
	{
		this.id = id;
	}

	public PbcatvldId getId()
	{
		return this.id;
	}

	public void setId(PbcatvldId id)
	{
		this.id = id;
	}

}
