package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * QcReagent generated by hbm2java
 */
public class QcReagent implements java.io.Serializable
{

	private int id;
	private String qcItem;
	private Date qcDate;
	private String reagentName;
	private Integer clientId;
	private String batchNo;
	private String result;
	private String resultA;
	private String resultB;
	private String resultO;
	private String resultUd;
	private String resultLd;
	private String aggreSize;
	private String aggreTime;
	private String result1;
	private String result2;
	private String result4;
	private String result8;
	private String result16;
	private String result32;
	private String result64;
	private String result128;
	private String result256;
	private String result512;
	private String result1024;
	private String abResult;
	private String operator;
	private String checker;
	private String remark;
	private String recordName;
	private Date recordTime;
	private Date validateDate;
	private String clientName;
	private Character status;

	public QcReagent()
	{
	}

	public QcReagent(int id, String qcItem, Date qcDate, String result)
	{
		this.id = id;
		this.qcItem = qcItem;
		this.qcDate = qcDate;
		this.result = result;
	}

	public QcReagent(int id, String qcItem, Date qcDate, String reagentName, Integer clientId, String batchNo,
			String result, String resultA, String resultB, String resultO, String resultUd, String resultLd,
			String aggreSize, String aggreTime, String result1, String result2, String result4, String result8,
			String result16, String result32, String result64, String result128, String result256, String result512,
			String result1024, String abResult, String operator, String checker, String remark, String recordName,
			Date recordTime, Date validateDate, String clientName, Character status)
	{
		this.id = id;
		this.qcItem = qcItem;
		this.qcDate = qcDate;
		this.reagentName = reagentName;
		this.clientId = clientId;
		this.batchNo = batchNo;
		this.result = result;
		this.resultA = resultA;
		this.resultB = resultB;
		this.resultO = resultO;
		this.resultUd = resultUd;
		this.resultLd = resultLd;
		this.aggreSize = aggreSize;
		this.aggreTime = aggreTime;
		this.result1 = result1;
		this.result2 = result2;
		this.result4 = result4;
		this.result8 = result8;
		this.result16 = result16;
		this.result32 = result32;
		this.result64 = result64;
		this.result128 = result128;
		this.result256 = result256;
		this.result512 = result512;
		this.result1024 = result1024;
		this.abResult = abResult;
		this.operator = operator;
		this.checker = checker;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
		this.validateDate = validateDate;
		this.clientName = clientName;
		this.status = status;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getQcItem()
	{
		return this.qcItem;
	}

	public void setQcItem(String qcItem)
	{
		this.qcItem = qcItem;
	}

	public Date getQcDate()
	{
		return this.qcDate;
	}

	public void setQcDate(Date qcDate)
	{
		this.qcDate = qcDate;
	}

	public String getReagentName()
	{
		return this.reagentName;
	}

	public void setReagentName(String reagentName)
	{
		this.reagentName = reagentName;
	}

	public Integer getClientId()
	{
		return this.clientId;
	}

	public void setClientId(Integer clientId)
	{
		this.clientId = clientId;
	}

	public String getBatchNo()
	{
		return this.batchNo;
	}

	public void setBatchNo(String batchNo)
	{
		this.batchNo = batchNo;
	}

	public String getResult()
	{
		return this.result;
	}

	public void setResult(String result)
	{
		this.result = result;
	}

	public String getResultA()
	{
		return this.resultA;
	}

	public void setResultA(String resultA)
	{
		this.resultA = resultA;
	}

	public String getResultB()
	{
		return this.resultB;
	}

	public void setResultB(String resultB)
	{
		this.resultB = resultB;
	}

	public String getResultO()
	{
		return this.resultO;
	}

	public void setResultO(String resultO)
	{
		this.resultO = resultO;
	}

	public String getResultUd()
	{
		return this.resultUd;
	}

	public void setResultUd(String resultUd)
	{
		this.resultUd = resultUd;
	}

	public String getResultLd()
	{
		return this.resultLd;
	}

	public void setResultLd(String resultLd)
	{
		this.resultLd = resultLd;
	}

	public String getAggreSize()
	{
		return this.aggreSize;
	}

	public void setAggreSize(String aggreSize)
	{
		this.aggreSize = aggreSize;
	}

	public String getAggreTime()
	{
		return this.aggreTime;
	}

	public void setAggreTime(String aggreTime)
	{
		this.aggreTime = aggreTime;
	}

	public String getResult1()
	{
		return this.result1;
	}

	public void setResult1(String result1)
	{
		this.result1 = result1;
	}

	public String getResult2()
	{
		return this.result2;
	}

	public void setResult2(String result2)
	{
		this.result2 = result2;
	}

	public String getResult4()
	{
		return this.result4;
	}

	public void setResult4(String result4)
	{
		this.result4 = result4;
	}

	public String getResult8()
	{
		return this.result8;
	}

	public void setResult8(String result8)
	{
		this.result8 = result8;
	}

	public String getResult16()
	{
		return this.result16;
	}

	public void setResult16(String result16)
	{
		this.result16 = result16;
	}

	public String getResult32()
	{
		return this.result32;
	}

	public void setResult32(String result32)
	{
		this.result32 = result32;
	}

	public String getResult64()
	{
		return this.result64;
	}

	public void setResult64(String result64)
	{
		this.result64 = result64;
	}

	public String getResult128()
	{
		return this.result128;
	}

	public void setResult128(String result128)
	{
		this.result128 = result128;
	}

	public String getResult256()
	{
		return this.result256;
	}

	public void setResult256(String result256)
	{
		this.result256 = result256;
	}

	public String getResult512()
	{
		return this.result512;
	}

	public void setResult512(String result512)
	{
		this.result512 = result512;
	}

	public String getResult1024()
	{
		return this.result1024;
	}

	public void setResult1024(String result1024)
	{
		this.result1024 = result1024;
	}

	public String getAbResult()
	{
		return this.abResult;
	}

	public void setAbResult(String abResult)
	{
		this.abResult = abResult;
	}

	public String getOperator()
	{
		return this.operator;
	}

	public void setOperator(String operator)
	{
		this.operator = operator;
	}

	public String getChecker()
	{
		return this.checker;
	}

	public void setChecker(String checker)
	{
		this.checker = checker;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public Date getValidateDate()
	{
		return this.validateDate;
	}

	public void setValidateDate(Date validateDate)
	{
		this.validateDate = validateDate;
	}

	public String getClientName()
	{
		return this.clientName;
	}

	public void setClientName(String clientName)
	{
		this.clientName = clientName;
	}

	public Character getStatus()
	{
		return this.status;
	}

	public void setStatus(Character status)
	{
		this.status = status;
	}

}
