package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * RcsBarcode generated by hbm2java
 */
public class RcsBarcode implements java.io.Serializable
{

	private int id;
	private int areaId;
	private String areaNo;
	private String barcode;
	private char printId;
	private String remark;
	private Date recordTime;
	private String recordName;

	public RcsBarcode()
	{
	}

	public RcsBarcode(int id, int areaId, String areaNo, String barcode, char printId)
	{
		this.id = id;
		this.areaId = areaId;
		this.areaNo = areaNo;
		this.barcode = barcode;
		this.printId = printId;
	}

	public RcsBarcode(int id, int areaId, String areaNo, String barcode, char printId, String remark, Date recordTime,
			String recordName)
	{
		this.id = id;
		this.areaId = areaId;
		this.areaNo = areaNo;
		this.barcode = barcode;
		this.printId = printId;
		this.remark = remark;
		this.recordTime = recordTime;
		this.recordName = recordName;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public int getAreaId()
	{
		return this.areaId;
	}

	public void setAreaId(int areaId)
	{
		this.areaId = areaId;
	}

	public String getAreaNo()
	{
		return this.areaNo;
	}

	public void setAreaNo(String areaNo)
	{
		this.areaNo = areaNo;
	}

	public String getBarcode()
	{
		return this.barcode;
	}

	public void setBarcode(String barcode)
	{
		this.barcode = barcode;
	}

	public char getPrintId()
	{
		return this.printId;
	}

	public void setPrintId(char printId)
	{
		this.printId = printId;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

}
