package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * RcsSampleInfo generated by hbm2java
 */
public class RcsSampleInfo implements java.io.Serializable
{

	private int id;
	private RcsBill rcsBill;
	private String sampleNo;
	private Integer sampleVol;
	private String numUnit;
	private Character receiveId;
	private Character okId;
	private Character nookResaon;
	private String remark;
	private Date recordTime;
	private String recordName;

	public RcsSampleInfo()
	{
	}

	public RcsSampleInfo(int id, RcsBill rcsBill, String sampleNo)
	{
		this.id = id;
		this.rcsBill = rcsBill;
		this.sampleNo = sampleNo;
	}

	public RcsSampleInfo(int id, RcsBill rcsBill, String sampleNo, Integer sampleVol, String numUnit,
			Character receiveId, Character okId, Character nookResaon, String remark, Date recordTime,
			String recordName)
	{
		this.id = id;
		this.rcsBill = rcsBill;
		this.sampleNo = sampleNo;
		this.sampleVol = sampleVol;
		this.numUnit = numUnit;
		this.receiveId = receiveId;
		this.okId = okId;
		this.nookResaon = nookResaon;
		this.remark = remark;
		this.recordTime = recordTime;
		this.recordName = recordName;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public RcsBill getRcsBill()
	{
		return this.rcsBill;
	}

	public void setRcsBill(RcsBill rcsBill)
	{
		this.rcsBill = rcsBill;
	}

	public String getSampleNo()
	{
		return this.sampleNo;
	}

	public void setSampleNo(String sampleNo)
	{
		this.sampleNo = sampleNo;
	}

	public Integer getSampleVol()
	{
		return this.sampleVol;
	}

	public void setSampleVol(Integer sampleVol)
	{
		this.sampleVol = sampleVol;
	}

	public String getNumUnit()
	{
		return this.numUnit;
	}

	public void setNumUnit(String numUnit)
	{
		this.numUnit = numUnit;
	}

	public Character getReceiveId()
	{
		return this.receiveId;
	}

	public void setReceiveId(Character receiveId)
	{
		this.receiveId = receiveId;
	}

	public Character getOkId()
	{
		return this.okId;
	}

	public void setOkId(Character okId)
	{
		this.okId = okId;
	}

	public Character getNookResaon()
	{
		return this.nookResaon;
	}

	public void setNookResaon(Character nookResaon)
	{
		this.nookResaon = nookResaon;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

}
