package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * ReactionTable generated by hbm2java
 */
public class ReactionTable implements java.io.Serializable
{

	private ReactionTableId id;

	public ReactionTable()
	{
	}

	public ReactionTable(ReactionTableId id)
	{
		this.id = id;
	}

	public ReactionTableId getId()
	{
		return this.id;
	}

	public void setId(ReactionTableId id)
	{
		this.id = id;
	}

}
