package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ResBloodType generated by hbm2java
 */
public class ResBloodType implements java.io.Serializable
{

	private int id;
	private CheckBill checkBill;
	private String name;
	private String bloodType;
	private String rhdRes;
	private String method;
	private String rhcRes;
	private String rhcLRes;
	private String rheRes;
	private String rheLRes;
	private String phenotype;
	private String remark;
	private String recordName;
	private Date recordTime;

	public ResBloodType()
	{
	}

	public ResBloodType(int id, CheckBill checkBill, String name, String bloodType, String rhdRes)
	{
		this.id = id;
		this.checkBill = checkBill;
		this.name = name;
		this.bloodType = bloodType;
		this.rhdRes = rhdRes;
	}

	public ResBloodType(int id, CheckBill checkBill, String name, String bloodType, String rhdRes, String method,
			String rhcRes, String rhcLRes, String rheRes, String rheLRes, String phenotype, String remark,
			String recordName, Date recordTime)
	{
		this.id = id;
		this.checkBill = checkBill;
		this.name = name;
		this.bloodType = bloodType;
		this.rhdRes = rhdRes;
		this.method = method;
		this.rhcRes = rhcRes;
		this.rhcLRes = rhcLRes;
		this.rheRes = rheRes;
		this.rheLRes = rheLRes;
		this.phenotype = phenotype;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public CheckBill getCheckBill()
	{
		return this.checkBill;
	}

	public void setCheckBill(CheckBill checkBill)
	{
		this.checkBill = checkBill;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getBloodType()
	{
		return this.bloodType;
	}

	public void setBloodType(String bloodType)
	{
		this.bloodType = bloodType;
	}

	public String getRhdRes()
	{
		return this.rhdRes;
	}

	public void setRhdRes(String rhdRes)
	{
		this.rhdRes = rhdRes;
	}

	public String getMethod()
	{
		return this.method;
	}

	public void setMethod(String method)
	{
		this.method = method;
	}

	public String getRhcRes()
	{
		return this.rhcRes;
	}

	public void setRhcRes(String rhcRes)
	{
		this.rhcRes = rhcRes;
	}

	public String getRhcLRes()
	{
		return this.rhcLRes;
	}

	public void setRhcLRes(String rhcLRes)
	{
		this.rhcLRes = rhcLRes;
	}

	public String getRheRes()
	{
		return this.rheRes;
	}

	public void setRheRes(String rheRes)
	{
		this.rheRes = rheRes;
	}

	public String getRheLRes()
	{
		return this.rheLRes;
	}

	public void setRheLRes(String rheLRes)
	{
		this.rheLRes = rheLRes;
	}

	public String getPhenotype()
	{
		return this.phenotype;
	}

	public void setPhenotype(String phenotype)
	{
		this.phenotype = phenotype;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

}
