package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * SamplePoint generated by hbm2java
 */
public class SamplePoint implements java.io.Serializable
{

	private int id;
	private Integer billId;
	private String sampleNo;
	private Character checkItem;
	private String point;
	private String remark;
	private Date recordTime;
	private String recordName;
	private Integer sampleId;

	public SamplePoint()
	{
	}

	public SamplePoint(int id)
	{
		this.id = id;
	}

	public SamplePoint(int id, Integer billId, String sampleNo, Character checkItem, String point, String remark,
			Date recordTime, String recordName, Integer sampleId)
	{
		this.id = id;
		this.billId = billId;
		this.sampleNo = sampleNo;
		this.checkItem = checkItem;
		this.point = point;
		this.remark = remark;
		this.recordTime = recordTime;
		this.recordName = recordName;
		this.sampleId = sampleId;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Integer getBillId()
	{
		return this.billId;
	}

	public void setBillId(Integer billId)
	{
		this.billId = billId;
	}

	public String getSampleNo()
	{
		return this.sampleNo;
	}

	public void setSampleNo(String sampleNo)
	{
		this.sampleNo = sampleNo;
	}

	public Character getCheckItem()
	{
		return this.checkItem;
	}

	public void setCheckItem(Character checkItem)
	{
		this.checkItem = checkItem;
	}

	public String getPoint()
	{
		return this.point;
	}

	public void setPoint(String point)
	{
		this.point = point;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Integer getSampleId()
	{
		return this.sampleId;
	}

	public void setSampleId(Integer sampleId)
	{
		this.sampleId = sampleId;
	}

}
