package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * SpecSample generated by hbm2java
 */
public class SpecSample implements java.io.Serializable
{

	private int id;
	private String no;
	private String sampleName;
	private String abo;
	private String rhdPhenotype;
	private String category;
	private String savePos;
	private Date saveDate;
	private String operName;
	private Integer num;
	private Date useDate;
	private Date recordTime;
	private String recordName;
	private String remark;

	public SpecSample()
	{
	}

	public SpecSample(int id, String no, Date saveDate)
	{
		this.id = id;
		this.no = no;
		this.saveDate = saveDate;
	}

	public SpecSample(int id, String no, String sampleName, String abo, String rhdPhenotype, String category,
			String savePos, Date saveDate, String operName, Integer num, Date useDate, Date recordTime,
			String recordName, String remark)
	{
		this.id = id;
		this.no = no;
		this.sampleName = sampleName;
		this.abo = abo;
		this.rhdPhenotype = rhdPhenotype;
		this.category = category;
		this.savePos = savePos;
		this.saveDate = saveDate;
		this.operName = operName;
		this.num = num;
		this.useDate = useDate;
		this.recordTime = recordTime;
		this.recordName = recordName;
		this.remark = remark;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getNo()
	{
		return this.no;
	}

	public void setNo(String no)
	{
		this.no = no;
	}

	public String getSampleName()
	{
		return this.sampleName;
	}

	public void setSampleName(String sampleName)
	{
		this.sampleName = sampleName;
	}

	public String getAbo()
	{
		return this.abo;
	}

	public void setAbo(String abo)
	{
		this.abo = abo;
	}

	public String getRhdPhenotype()
	{
		return this.rhdPhenotype;
	}

	public void setRhdPhenotype(String rhdPhenotype)
	{
		this.rhdPhenotype = rhdPhenotype;
	}

	public String getCategory()
	{
		return this.category;
	}

	public void setCategory(String category)
	{
		this.category = category;
	}

	public String getSavePos()
	{
		return this.savePos;
	}

	public void setSavePos(String savePos)
	{
		this.savePos = savePos;
	}

	public Date getSaveDate()
	{
		return this.saveDate;
	}

	public void setSaveDate(Date saveDate)
	{
		this.saveDate = saveDate;
	}

	public String getOperName()
	{
		return this.operName;
	}

	public void setOperName(String operName)
	{
		this.operName = operName;
	}

	public Integer getNum()
	{
		return this.num;
	}

	public void setNum(Integer num)
	{
		this.num = num;
	}

	public Date getUseDate()
	{
		return this.useDate;
	}

	public void setUseDate(Date useDate)
	{
		this.useDate = useDate;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

}
