package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * SysParam generated by hbm2java
 */
public class SysParam implements java.io.Serializable
{

	private int id;
	private String code;
	private String name;
	private String value;
	private String remark;
	private String recordName;
	private Date recordTime;
	private Character valType;

	public SysParam()
	{
	}

	public SysParam(int id, String code, String name, String value)
	{
		this.id = id;
		this.code = code;
		this.name = name;
		this.value = value;
	}

	public SysParam(int id, String code, String name, String value, String remark, String recordName, Date recordTime,
			Character valType)
	{
		this.id = id;
		this.code = code;
		this.name = name;
		this.value = value;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
		this.valType = valType;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getValue()
	{
		return this.value;
	}

	public void setValue(String value)
	{
		this.value = value;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public Character getValType()
	{
		return this.valType;
	}

	public void setValType(Character valType)
	{
		this.valType = valType;
	}

}
