package riswell.model;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * VDa generated by hbm2java
 */
public class VDa implements java.io.Serializable
{

	private VDaId id;

	public VDa()
	{
	}

	public VDa(VDaId id)
	{
		this.id = id;
	}

	public VDaId getId()
	{
		return this.id;
	}

	public void setId(VDaId id)
	{
		this.id = id;
	}

}
