package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * BoardGrid generated by hbm2java
 */
public class BoardGrid implements java.io.Serializable
{

	private int id;
	private Integer operId;
	private String boardNo;
	private char operType;
	private char billKind;
	private String code;
	private int no;
	private String barcode;
	private String point;
	private Character rcsId;
	private String pcrS;
	private String pcrS1;
	private String pcrS2;
	private String secore;
	private String seqNo;
	private String secoreName;
	private Character lowId;
	private Character dbId;
	private String remark;
	private Date recordTime;
	private String recordName;
	private Integer forPoint;

	public BoardGrid()
	{
	}

	public BoardGrid(int id, String boardNo, char operType, char billKind, int no)
	{
		this.id = id;
		this.boardNo = boardNo;
		this.operType = operType;
		this.billKind = billKind;
		this.no = no;
	}

	public BoardGrid(int id, Integer operId, String boardNo, char operType, char billKind, String code, int no,
			String barcode, String point, Character rcsId, String pcrS, String pcrS1, String pcrS2, String secore,
			String seqNo, String secoreName, Character lowId, Character dbId, String remark, Date recordTime,
			String recordName, Integer forPoint)
	{
		this.id = id;
		this.operId = operId;
		this.boardNo = boardNo;
		this.operType = operType;
		this.billKind = billKind;
		this.code = code;
		this.no = no;
		this.barcode = barcode;
		this.point = point;
		this.rcsId = rcsId;
		this.pcrS = pcrS;
		this.pcrS1 = pcrS1;
		this.pcrS2 = pcrS2;
		this.secore = secore;
		this.seqNo = seqNo;
		this.secoreName = secoreName;
		this.lowId = lowId;
		this.dbId = dbId;
		this.remark = remark;
		this.recordTime = recordTime;
		this.recordName = recordName;
		this.forPoint = forPoint;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Integer getOperId()
	{
		return this.operId;
	}

	public void setOperId(Integer operId)
	{
		this.operId = operId;
	}

	public String getBoardNo()
	{
		return this.boardNo;
	}

	public void setBoardNo(String boardNo)
	{
		this.boardNo = boardNo;
	}

	public char getOperType()
	{
		return this.operType;
	}

	public void setOperType(char operType)
	{
		this.operType = operType;
	}

	public char getBillKind()
	{
		return this.billKind;
	}

	public void setBillKind(char billKind)
	{
		this.billKind = billKind;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public int getNo()
	{
		return this.no;
	}

	public void setNo(int no)
	{
		this.no = no;
	}

	public String getBarcode()
	{
		return this.barcode;
	}

	public void setBarcode(String barcode)
	{
		this.barcode = barcode;
	}

	public String getPoint()
	{
		return this.point;
	}

	public void setPoint(String point)
	{
		this.point = point;
	}

	public Character getRcsId()
	{
		return this.rcsId;
	}

	public void setRcsId(Character rcsId)
	{
		this.rcsId = rcsId;
	}

	public String getPcrS()
	{
		return this.pcrS;
	}

	public void setPcrS(String pcrS)
	{
		this.pcrS = pcrS;
	}

	public String getPcrS1()
	{
		return this.pcrS1;
	}

	public void setPcrS1(String pcrS1)
	{
		this.pcrS1 = pcrS1;
	}

	public String getPcrS2()
	{
		return this.pcrS2;
	}

	public void setPcrS2(String pcrS2)
	{
		this.pcrS2 = pcrS2;
	}

	public String getSecore()
	{
		return this.secore;
	}

	public void setSecore(String secore)
	{
		this.secore = secore;
	}

	public String getSeqNo()
	{
		return this.seqNo;
	}

	public void setSeqNo(String seqNo)
	{
		this.seqNo = seqNo;
	}

	public String getSecoreName()
	{
		return this.secoreName;
	}

	public void setSecoreName(String secoreName)
	{
		this.secoreName = secoreName;
	}

	public Character getLowId()
	{
		return this.lowId;
	}

	public void setLowId(Character lowId)
	{
		this.lowId = lowId;
	}

	public Character getDbId()
	{
		return this.dbId;
	}

	public void setDbId(Character dbId)
	{
		this.dbId = dbId;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Integer getForPoint()
	{
		return this.forPoint;
	}

	public void setForPoint(Integer forPoint)
	{
		this.forPoint = forPoint;
	}

}
