package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * CenterBill generated by hbm2java
 */
public class CenterBill implements java.io.Serializable
{

	private int id;
	private Date notifyDate;
	private String notifyType;
	private String patientNo;
	private String patientName;
	private String providerNo;
	private String providerName;
	private String reqDoctor;
	private String hospitalName;
	private String hpReceipt;
	private Date hpViewDate;
	private Date hpReceiptDate;
	private String whName;
	private String whReceipt;
	private Date whViewDate;
	private Date whReceiptDate;
	private char billId;
	private String billNo;
	private String remark;
	private Date recordTime;
	private String recordName;
	private String highLab;
	private Date highTime;

	public CenterBill()
	{
	}

	public CenterBill(int id, Date notifyDate, String patientNo, String providerNo, char billId)
	{
		this.id = id;
		this.notifyDate = notifyDate;
		this.patientNo = patientNo;
		this.providerNo = providerNo;
		this.billId = billId;
	}

	public CenterBill(int id, Date notifyDate, String notifyType, String patientNo, String patientName,
			String providerNo, String providerName, String reqDoctor, String hospitalName, String hpReceipt,
			Date hpViewDate, Date hpReceiptDate, String whName, String whReceipt, Date whViewDate, Date whReceiptDate,
			char billId, String billNo, String remark, Date recordTime, String recordName, String highLab,
			Date highTime)
	{
		this.id = id;
		this.notifyDate = notifyDate;
		this.notifyType = notifyType;
		this.patientNo = patientNo;
		this.patientName = patientName;
		this.providerNo = providerNo;
		this.providerName = providerName;
		this.reqDoctor = reqDoctor;
		this.hospitalName = hospitalName;
		this.hpReceipt = hpReceipt;
		this.hpViewDate = hpViewDate;
		this.hpReceiptDate = hpReceiptDate;
		this.whName = whName;
		this.whReceipt = whReceipt;
		this.whViewDate = whViewDate;
		this.whReceiptDate = whReceiptDate;
		this.billId = billId;
		this.billNo = billNo;
		this.remark = remark;
		this.recordTime = recordTime;
		this.recordName = recordName;
		this.highLab = highLab;
		this.highTime = highTime;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Date getNotifyDate()
	{
		return this.notifyDate;
	}

	public void setNotifyDate(Date notifyDate)
	{
		this.notifyDate = notifyDate;
	}

	public String getNotifyType()
	{
		return this.notifyType;
	}

	public void setNotifyType(String notifyType)
	{
		this.notifyType = notifyType;
	}

	public String getPatientNo()
	{
		return this.patientNo;
	}

	public void setPatientNo(String patientNo)
	{
		this.patientNo = patientNo;
	}

	public String getPatientName()
	{
		return this.patientName;
	}

	public void setPatientName(String patientName)
	{
		this.patientName = patientName;
	}

	public String getProviderNo()
	{
		return this.providerNo;
	}

	public void setProviderNo(String providerNo)
	{
		this.providerNo = providerNo;
	}

	public String getProviderName()
	{
		return this.providerName;
	}

	public void setProviderName(String providerName)
	{
		this.providerName = providerName;
	}

	public String getReqDoctor()
	{
		return this.reqDoctor;
	}

	public void setReqDoctor(String reqDoctor)
	{
		this.reqDoctor = reqDoctor;
	}

	public String getHospitalName()
	{
		return this.hospitalName;
	}

	public void setHospitalName(String hospitalName)
	{
		this.hospitalName = hospitalName;
	}

	public String getHpReceipt()
	{
		return this.hpReceipt;
	}

	public void setHpReceipt(String hpReceipt)
	{
		this.hpReceipt = hpReceipt;
	}

	public Date getHpViewDate()
	{
		return this.hpViewDate;
	}

	public void setHpViewDate(Date hpViewDate)
	{
		this.hpViewDate = hpViewDate;
	}

	public Date getHpReceiptDate()
	{
		return this.hpReceiptDate;
	}

	public void setHpReceiptDate(Date hpReceiptDate)
	{
		this.hpReceiptDate = hpReceiptDate;
	}

	public String getWhName()
	{
		return this.whName;
	}

	public void setWhName(String whName)
	{
		this.whName = whName;
	}

	public String getWhReceipt()
	{
		return this.whReceipt;
	}

	public void setWhReceipt(String whReceipt)
	{
		this.whReceipt = whReceipt;
	}

	public Date getWhViewDate()
	{
		return this.whViewDate;
	}

	public void setWhViewDate(Date whViewDate)
	{
		this.whViewDate = whViewDate;
	}

	public Date getWhReceiptDate()
	{
		return this.whReceiptDate;
	}

	public void setWhReceiptDate(Date whReceiptDate)
	{
		this.whReceiptDate = whReceiptDate;
	}

	public char getBillId()
	{
		return this.billId;
	}

	public void setBillId(char billId)
	{
		this.billId = billId;
	}

	public String getBillNo()
	{
		return this.billNo;
	}

	public void setBillNo(String billNo)
	{
		this.billNo = billNo;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public String getHighLab()
	{
		return this.highLab;
	}

	public void setHighLab(String highLab)
	{
		this.highLab = highLab;
	}

	public Date getHighTime()
	{
		return this.highTime;
	}

	public void setHighTime(Date highTime)
	{
		this.highTime = highTime;
	}

}
