package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * CheckBillFee generated by hbm2java
 */
public class CheckBillFee implements java.io.Serializable
{

	private int id;
	private CheckBill checkBill;
	private String billNo;
	private String itemCode;
	private Integer nums;
	private BigDecimal price;
	private String remark;
	private Date recordTime;
	private String recordName;
	private Character operType;

	public CheckBillFee()
	{
	}

	public CheckBillFee(int id)
	{
		this.id = id;
	}

	public CheckBillFee(int id, CheckBill checkBill, String billNo, String itemCode, Integer nums, BigDecimal price,
			String remark, Date recordTime, String recordName, Character operType)
	{
		this.id = id;
		this.checkBill = checkBill;
		this.billNo = billNo;
		this.itemCode = itemCode;
		this.nums = nums;
		this.price = price;
		this.remark = remark;
		this.recordTime = recordTime;
		this.recordName = recordName;
		this.operType = operType;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public CheckBill getCheckBill()
	{
		return this.checkBill;
	}

	public void setCheckBill(CheckBill checkBill)
	{
		this.checkBill = checkBill;
	}

	public String getBillNo()
	{
		return this.billNo;
	}

	public void setBillNo(String billNo)
	{
		this.billNo = billNo;
	}

	public String getItemCode()
	{
		return this.itemCode;
	}

	public void setItemCode(String itemCode)
	{
		this.itemCode = itemCode;
	}

	public Integer getNums()
	{
		return this.nums;
	}

	public void setNums(Integer nums)
	{
		this.nums = nums;
	}

	public BigDecimal getPrice()
	{
		return this.price;
	}

	public void setPrice(BigDecimal price)
	{
		this.price = price;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Character getOperType()
	{
		return this.operType;
	}

	public void setOperType(Character operType)
	{
		this.operType = operType;
	}

}
