package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * CheckSample generated by hbm2java
 */
public class CheckSample implements java.io.Serializable
{

	private int id;
	private Integer checkBillId;
	private Integer requestBillId;
	private String no;
	private String bloodNo;
	private String abo;
	private Date acceptDate;
	private String checkItem;
	private String acceptMan;
	private Character result;
	private String reason;
	private String remark;
	private String recordName;
	private Date recordTime;
	private String phenotype;
	private Character rhdRes;
	private String abRes;
	private String antibodyScreening;

	public CheckSample()
	{
	}

	public CheckSample(int id, String checkItem)
	{
		this.id = id;
		this.checkItem = checkItem;
	}

	public CheckSample(int id, Integer checkBillId, Integer requestBillId, String no, String bloodNo, String abo,
			Date acceptDate, String checkItem, String acceptMan, Character result, String reason, String remark,
			String recordName, Date recordTime, String phenotype, Character rhdRes, String abRes,
			String antibodyScreening)
	{
		this.id = id;
		this.checkBillId = checkBillId;
		this.requestBillId = requestBillId;
		this.no = no;
		this.bloodNo = bloodNo;
		this.abo = abo;
		this.acceptDate = acceptDate;
		this.checkItem = checkItem;
		this.acceptMan = acceptMan;
		this.result = result;
		this.reason = reason;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
		this.phenotype = phenotype;
		this.rhdRes = rhdRes;
		this.abRes = abRes;
		this.antibodyScreening = antibodyScreening;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Integer getCheckBillId()
	{
		return this.checkBillId;
	}

	public void setCheckBillId(Integer checkBillId)
	{
		this.checkBillId = checkBillId;
	}

	public Integer getRequestBillId()
	{
		return this.requestBillId;
	}

	public void setRequestBillId(Integer requestBillId)
	{
		this.requestBillId = requestBillId;
	}

	public String getNo()
	{
		return this.no;
	}

	public void setNo(String no)
	{
		this.no = no;
	}

	public String getBloodNo()
	{
		return this.bloodNo;
	}

	public void setBloodNo(String bloodNo)
	{
		this.bloodNo = bloodNo;
	}

	public String getAbo()
	{
		return this.abo;
	}

	public void setAbo(String abo)
	{
		this.abo = abo;
	}

	public Date getAcceptDate()
	{
		return this.acceptDate;
	}

	public void setAcceptDate(Date acceptDate)
	{
		this.acceptDate = acceptDate;
	}

	public String getCheckItem()
	{
		return this.checkItem;
	}

	public void setCheckItem(String checkItem)
	{
		this.checkItem = checkItem;
	}

	public String getAcceptMan()
	{
		return this.acceptMan;
	}

	public void setAcceptMan(String acceptMan)
	{
		this.acceptMan = acceptMan;
	}

	public Character getResult()
	{
		return this.result;
	}

	public void setResult(Character result)
	{
		this.result = result;
	}

	public String getReason()
	{
		return this.reason;
	}

	public void setReason(String reason)
	{
		this.reason = reason;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getPhenotype()
	{
		return this.phenotype;
	}

	public void setPhenotype(String phenotype)
	{
		this.phenotype = phenotype;
	}

	public Character getRhdRes()
	{
		return this.rhdRes;
	}

	public void setRhdRes(Character rhdRes)
	{
		this.rhdRes = rhdRes;
	}

	public String getAbRes()
	{
		return this.abRes;
	}

	public void setAbRes(String abRes)
	{
		this.abRes = abRes;
	}

	public String getAntibodyScreening()
	{
		return this.antibodyScreening;
	}

	public void setAntibodyScreening(String antibodyScreening)
	{
		this.antibodyScreening = antibodyScreening;
	}

}
