package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * CheckBillFeeMonth generated by hbm2java
 */
public class CheckBillFeeMonth implements java.io.Serializable
{

	private int id;
	private CheckBillMonth checkBillMonth;
	private String billNo;
	private String itemCode;
	private BigDecimal nums;
	private BigDecimal price;
	private String remark;
	private Date recordTime;
	private String recordName;
	private Character operType;

	public CheckBillFeeMonth()
	{
	}

	public CheckBillFeeMonth(int id, BigDecimal nums)
	{
		this.id = id;
		this.nums = nums;
	}

	public CheckBillFeeMonth(int id, CheckBillMonth checkBillMonth, String billNo, String itemCode, BigDecimal nums,
			BigDecimal price, String remark, Date recordTime, String recordName, Character operType)
	{
		this.id = id;
		this.checkBillMonth = checkBillMonth;
		this.billNo = billNo;
		this.itemCode = itemCode;
		this.nums = nums;
		this.price = price;
		this.remark = remark;
		this.recordTime = recordTime;
		this.recordName = recordName;
		this.operType = operType;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public CheckBillMonth getCheckBillMonth()
	{
		return this.checkBillMonth;
	}

	public void setCheckBillMonth(CheckBillMonth checkBillMonth)
	{
		this.checkBillMonth = checkBillMonth;
	}

	public String getBillNo()
	{
		return this.billNo;
	}

	public void setBillNo(String billNo)
	{
		this.billNo = billNo;
	}

	public String getItemCode()
	{
		return this.itemCode;
	}

	public void setItemCode(String itemCode)
	{
		this.itemCode = itemCode;
	}

	public BigDecimal getNums()
	{
		return this.nums;
	}

	public void setNums(BigDecimal nums)
	{
		this.nums = nums;
	}

	public BigDecimal getPrice()
	{
		return this.price;
	}

	public void setPrice(BigDecimal price)
	{
		this.price = price;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Character getOperType()
	{
		return this.operType;
	}

	public void setOperType(Character operType)
	{
		this.operType = operType;
	}

}
