package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

/**
 * CImgtT generated by hbm2java
 */
public class CImgtT implements java.io.Serializable
{

	private CImgtTId id;

	public CImgtT()
	{
	}

	public CImgtT(CImgtTId id)
	{
		this.id = id;
	}

	public CImgtTId getId()
	{
		return this.id;
	}

	public void setId(CImgtTId id)
	{
		this.id = id;
	}

}
