package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * CImgtDetailTId generated by hbm2java
 */
public class CImgtDetailTId implements java.io.Serializable
{

	private int id;
	private int imgtId;
	private String sampleNo;
	private String point;
	private String sbtResult;
	private String ssopResult;
	private String imgtStatus;
	private String recordName;
	private Date recordDate;
	private String remark;

	public CImgtDetailTId()
	{
	}

	public CImgtDetailTId(int id, int imgtId)
	{
		this.id = id;
		this.imgtId = imgtId;
	}

	public CImgtDetailTId(int id, int imgtId, String sampleNo, String point, String sbtResult, String ssopResult,
			String imgtStatus, String recordName, Date recordDate, String remark)
	{
		this.id = id;
		this.imgtId = imgtId;
		this.sampleNo = sampleNo;
		this.point = point;
		this.sbtResult = sbtResult;
		this.ssopResult = ssopResult;
		this.imgtStatus = imgtStatus;
		this.recordName = recordName;
		this.recordDate = recordDate;
		this.remark = remark;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public int getImgtId()
	{
		return this.imgtId;
	}

	public void setImgtId(int imgtId)
	{
		this.imgtId = imgtId;
	}

	public String getSampleNo()
	{
		return this.sampleNo;
	}

	public void setSampleNo(String sampleNo)
	{
		this.sampleNo = sampleNo;
	}

	public String getPoint()
	{
		return this.point;
	}

	public void setPoint(String point)
	{
		this.point = point;
	}

	public String getSbtResult()
	{
		return this.sbtResult;
	}

	public void setSbtResult(String sbtResult)
	{
		this.sbtResult = sbtResult;
	}

	public String getSsopResult()
	{
		return this.ssopResult;
	}

	public void setSsopResult(String ssopResult)
	{
		this.ssopResult = ssopResult;
	}

	public String getImgtStatus()
	{
		return this.imgtStatus;
	}

	public void setImgtStatus(String imgtStatus)
	{
		this.imgtStatus = imgtStatus;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordDate()
	{
		return this.recordDate;
	}

	public void setRecordDate(Date recordDate)
	{
		this.recordDate = recordDate;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CImgtDetailTId))
			return false;
		CImgtDetailTId castOther = (CImgtDetailTId) other;

		return (this.getId() == castOther.getId()) && (this.getImgtId() == castOther.getImgtId())
				&& ((this.getSampleNo() == castOther.getSampleNo()) || (this.getSampleNo() != null
						&& castOther.getSampleNo() != null && this.getSampleNo().equals(castOther.getSampleNo())))
				&& ((this.getPoint() == castOther.getPoint()) || (this.getPoint() != null
						&& castOther.getPoint() != null && this.getPoint().equals(castOther.getPoint())))
				&& ((this.getSbtResult() == castOther.getSbtResult()) || (this.getSbtResult() != null
						&& castOther.getSbtResult() != null && this.getSbtResult().equals(castOther.getSbtResult())))
				&& ((this.getSsopResult() == castOther.getSsopResult()) || (this.getSsopResult() != null
						&& castOther.getSsopResult() != null && this.getSsopResult().equals(castOther.getSsopResult())))
				&& ((this.getImgtStatus() == castOther.getImgtStatus()) || (this.getImgtStatus() != null
						&& castOther.getImgtStatus() != null && this.getImgtStatus().equals(castOther.getImgtStatus())))
				&& ((this.getRecordName() == castOther.getRecordName()) || (this.getRecordName() != null
						&& castOther.getRecordName() != null && this.getRecordName().equals(castOther.getRecordName())))
				&& ((this.getRecordDate() == castOther.getRecordDate()) || (this.getRecordDate() != null
						&& castOther.getRecordDate() != null && this.getRecordDate().equals(castOther.getRecordDate())))
				&& ((this.getRemark() == castOther.getRemark()) || (this.getRemark() != null
						&& castOther.getRemark() != null && this.getRemark().equals(castOther.getRemark())));
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getImgtId();
		result = 37 * result + (getSampleNo() == null ? 0 : this.getSampleNo().hashCode());
		result = 37 * result + (getPoint() == null ? 0 : this.getPoint().hashCode());
		result = 37 * result + (getSbtResult() == null ? 0 : this.getSbtResult().hashCode());
		result = 37 * result + (getSsopResult() == null ? 0 : this.getSsopResult().hashCode());
		result = 37 * result + (getImgtStatus() == null ? 0 : this.getImgtStatus().hashCode());
		result = 37 * result + (getRecordName() == null ? 0 : this.getRecordName().hashCode());
		result = 37 * result + (getRecordDate() == null ? 0 : this.getRecordDate().hashCode());
		result = 37 * result + (getRemark() == null ? 0 : this.getRemark().hashCode());
		return result;
	}

}
