package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * CInvoiceRecordT generated by hbm2java
 */
public class CInvoiceRecordT implements java.io.Serializable
{

	private CInvoiceRecordTId id;

	public CInvoiceRecordT()
	{
	}

	public CInvoiceRecordT(CInvoiceRecordTId id)
	{
		this.id = id;
	}

	public CInvoiceRecordTId getId()
	{
		return this.id;
	}

	public void setId(CInvoiceRecordTId id)
	{
		this.id = id;
	}

}
