package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

/**
 * CReplaceT generated by hbm2java
 */
public class CReplaceT implements java.io.Serializable
{

	private CReplaceTId id;

	public CReplaceT()
	{
	}

	public CReplaceT(CReplaceTId id)
	{
		this.id = id;
	}

	public CReplaceTId getId()
	{
		return this.id;
	}

	public void setId(CReplaceTId id)
	{
		this.id = id;
	}

}
