package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

/**
 * CRuleAmbiguityDetailT generated by hbm2java
 */
public class CRuleAmbiguityDetailT implements java.io.Serializable
{

	private CRuleAmbiguityDetailTId id;

	public CRuleAmbiguityDetailT()
	{
	}

	public CRuleAmbiguityDetailT(CRuleAmbiguityDetailTId id)
	{
		this.id = id;
	}

	public CRuleAmbiguityDetailTId getId()
	{
		return this.id;
	}

	public void setId(CRuleAmbiguityDetailTId id)
	{
		this.id = id;
	}

}
