package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * CRuleCwdDetailT generated by hbm2java
 */
public class CRuleCwdDetailT implements java.io.Serializable
{

	private CRuleCwdDetailTId id;

	public CRuleCwdDetailT()
	{
	}

	public CRuleCwdDetailT(CRuleCwdDetailTId id)
	{
		this.id = id;
	}

	public CRuleCwdDetailTId getId()
	{
		return this.id;
	}

	public void setId(CRuleCwdDetailTId id)
	{
		this.id = id;
	}

}
