package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * CRuleAmbiguityDetailTId generated by hbm2java
 */
public class CRuleAmbiguityDetailTId implements java.io.Serializable
{

	private int id;
	private int ruleId;
	private String alleleName;
	private String otherAllele;
	private String point;
	private String ruleResult;
	private String recordName;
	private Date recordDate;
	private String remark;
	private String ruleFlag;

	public CRuleAmbiguityDetailTId()
	{
	}

	public CRuleAmbiguityDetailTId(int id, int ruleId)
	{
		this.id = id;
		this.ruleId = ruleId;
	}

	public CRuleAmbiguityDetailTId(int id, int ruleId, String alleleName, String otherAllele, String point,
			String ruleResult, String recordName, Date recordDate, String remark, String ruleFlag)
	{
		this.id = id;
		this.ruleId = ruleId;
		this.alleleName = alleleName;
		this.otherAllele = otherAllele;
		this.point = point;
		this.ruleResult = ruleResult;
		this.recordName = recordName;
		this.recordDate = recordDate;
		this.remark = remark;
		this.ruleFlag = ruleFlag;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public int getRuleId()
	{
		return this.ruleId;
	}

	public void setRuleId(int ruleId)
	{
		this.ruleId = ruleId;
	}

	public String getAlleleName()
	{
		return this.alleleName;
	}

	public void setAlleleName(String alleleName)
	{
		this.alleleName = alleleName;
	}

	public String getOtherAllele()
	{
		return this.otherAllele;
	}

	public void setOtherAllele(String otherAllele)
	{
		this.otherAllele = otherAllele;
	}

	public String getPoint()
	{
		return this.point;
	}

	public void setPoint(String point)
	{
		this.point = point;
	}

	public String getRuleResult()
	{
		return this.ruleResult;
	}

	public void setRuleResult(String ruleResult)
	{
		this.ruleResult = ruleResult;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordDate()
	{
		return this.recordDate;
	}

	public void setRecordDate(Date recordDate)
	{
		this.recordDate = recordDate;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRuleFlag()
	{
		return this.ruleFlag;
	}

	public void setRuleFlag(String ruleFlag)
	{
		this.ruleFlag = ruleFlag;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CRuleAmbiguityDetailTId))
			return false;
		CRuleAmbiguityDetailTId castOther = (CRuleAmbiguityDetailTId) other;

		return (this.getId() == castOther.getId()) && (this.getRuleId() == castOther.getRuleId())
				&& ((this.getAlleleName() == castOther.getAlleleName()) || (this.getAlleleName() != null
						&& castOther.getAlleleName() != null && this.getAlleleName().equals(castOther.getAlleleName())))
				&& ((this.getOtherAllele() == castOther.getOtherAllele())
						|| (this.getOtherAllele() != null && castOther.getOtherAllele() != null
								&& this.getOtherAllele().equals(castOther.getOtherAllele())))
				&& ((this.getPoint() == castOther.getPoint()) || (this.getPoint() != null
						&& castOther.getPoint() != null && this.getPoint().equals(castOther.getPoint())))
				&& ((this.getRuleResult() == castOther.getRuleResult()) || (this.getRuleResult() != null
						&& castOther.getRuleResult() != null && this.getRuleResult().equals(castOther.getRuleResult())))
				&& ((this.getRecordName() == castOther.getRecordName()) || (this.getRecordName() != null
						&& castOther.getRecordName() != null && this.getRecordName().equals(castOther.getRecordName())))
				&& ((this.getRecordDate() == castOther.getRecordDate()) || (this.getRecordDate() != null
						&& castOther.getRecordDate() != null && this.getRecordDate().equals(castOther.getRecordDate())))
				&& ((this.getRemark() == castOther.getRemark()) || (this.getRemark() != null
						&& castOther.getRemark() != null && this.getRemark().equals(castOther.getRemark())))
				&& ((this.getRuleFlag() == castOther.getRuleFlag()) || (this.getRuleFlag() != null
						&& castOther.getRuleFlag() != null && this.getRuleFlag().equals(castOther.getRuleFlag())));
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getRuleId();
		result = 37 * result + (getAlleleName() == null ? 0 : this.getAlleleName().hashCode());
		result = 37 * result + (getOtherAllele() == null ? 0 : this.getOtherAllele().hashCode());
		result = 37 * result + (getPoint() == null ? 0 : this.getPoint().hashCode());
		result = 37 * result + (getRuleResult() == null ? 0 : this.getRuleResult().hashCode());
		result = 37 * result + (getRecordName() == null ? 0 : this.getRecordName().hashCode());
		result = 37 * result + (getRecordDate() == null ? 0 : this.getRecordDate().hashCode());
		result = 37 * result + (getRemark() == null ? 0 : this.getRemark().hashCode());
		result = 37 * result + (getRuleFlag() == null ? 0 : this.getRuleFlag().hashCode());
		return result;
	}

}
