package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

/**
 * CRuleAlleleT generated by hbm2java
 */
public class CRuleAlleleT implements java.io.Serializable
{

	private CRuleAlleleTId id;

	public CRuleAlleleT()
	{
	}

	public CRuleAlleleT(CRuleAlleleTId id)
	{
		this.id = id;
	}

	public CRuleAlleleTId getId()
	{
		return this.id;
	}

	public void setId(CRuleAlleleTId id)
	{
		this.id = id;
	}

}
