package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * CRuleResourceT generated by hbm2java
 */
public class CRuleResourceT implements java.io.Serializable
{

	private CRuleResourceTId id;

	public CRuleResourceT()
	{
	}

	public CRuleResourceT(CRuleResourceTId id)
	{
		this.id = id;
	}

	public CRuleResourceTId getId()
	{
		return this.id;
	}

	public void setId(CRuleResourceTId id)
	{
		this.id = id;
	}

}
