package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * DeptReport generated by hbm2java
 */
public class DeptReport implements java.io.Serializable
{

	private int id;
	private Integer deptId;
	private String billNo;
	private String billMan;
	private Date billDate;
	private String remark;
	private String recordName;
	private Date recordTime;

	public DeptReport()
	{
	}

	public DeptReport(int id)
	{
		this.id = id;
	}

	public DeptReport(int id, Integer deptId, String billNo, String billMan, Date billDate, String remark,
			String recordName, Date recordTime)
	{
		this.id = id;
		this.deptId = deptId;
		this.billNo = billNo;
		this.billMan = billMan;
		this.billDate = billDate;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Integer getDeptId()
	{
		return this.deptId;
	}

	public void setDeptId(Integer deptId)
	{
		this.deptId = deptId;
	}

	public String getBillNo()
	{
		return this.billNo;
	}

	public void setBillNo(String billNo)
	{
		this.billNo = billNo;
	}

	public String getBillMan()
	{
		return this.billMan;
	}

	public void setBillMan(String billMan)
	{
		this.billMan = billMan;
	}

	public Date getBillDate()
	{
		return this.billDate;
	}

	public void setBillDate(Date billDate)
	{
		this.billDate = billDate;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

}
