package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * EquipmentAdjust generated by hbm2java
 */
public class EquipmentAdjust implements java.io.Serializable
{

	private int id;
	private int equipmentId;
	private String adjustUnit;
	private String adjustMan;
	private Date adjustDate;
	private Character result;
	private String remark;
	private String recordName;
	private Date recordTime;

	public EquipmentAdjust()
	{
	}

	public EquipmentAdjust(int id, int equipmentId)
	{
		this.id = id;
		this.equipmentId = equipmentId;
	}

	public EquipmentAdjust(int id, int equipmentId, String adjustUnit, String adjustMan, Date adjustDate,
			Character result, String remark, String recordName, Date recordTime)
	{
		this.id = id;
		this.equipmentId = equipmentId;
		this.adjustUnit = adjustUnit;
		this.adjustMan = adjustMan;
		this.adjustDate = adjustDate;
		this.result = result;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public int getEquipmentId()
	{
		return this.equipmentId;
	}

	public void setEquipmentId(int equipmentId)
	{
		this.equipmentId = equipmentId;
	}

	public String getAdjustUnit()
	{
		return this.adjustUnit;
	}

	public void setAdjustUnit(String adjustUnit)
	{
		this.adjustUnit = adjustUnit;
	}

	public String getAdjustMan()
	{
		return this.adjustMan;
	}

	public void setAdjustMan(String adjustMan)
	{
		this.adjustMan = adjustMan;
	}

	public Date getAdjustDate()
	{
		return this.adjustDate;
	}

	public void setAdjustDate(Date adjustDate)
	{
		this.adjustDate = adjustDate;
	}

	public Character getResult()
	{
		return this.result;
	}

	public void setResult(Character result)
	{
		this.result = result;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

}
