package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * FeeRecord generated by hbm2java
 */
public class FeeRecord implements java.io.Serializable
{

	private int id;
	private Date feeDate;
	private String name;
	private String accountNo;
	private BigDecimal amount;
	private Character feeType;
	private String remark;
	private Date recordTime;
	private String recordName;
	private String feeName;
	private String useInfo;
	private BigDecimal backAmount;
	private String seqNo;

	public FeeRecord()
	{
	}

	public FeeRecord(int id, Date feeDate, String name, BigDecimal amount)
	{
		this.id = id;
		this.feeDate = feeDate;
		this.name = name;
		this.amount = amount;
	}

	public FeeRecord(int id, Date feeDate, String name, String accountNo, BigDecimal amount, Character feeType,
			String remark, Date recordTime, String recordName, String feeName, String useInfo, BigDecimal backAmount,
			String seqNo)
	{
		this.id = id;
		this.feeDate = feeDate;
		this.name = name;
		this.accountNo = accountNo;
		this.amount = amount;
		this.feeType = feeType;
		this.remark = remark;
		this.recordTime = recordTime;
		this.recordName = recordName;
		this.feeName = feeName;
		this.useInfo = useInfo;
		this.backAmount = backAmount;
		this.seqNo = seqNo;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Date getFeeDate()
	{
		return this.feeDate;
	}

	public void setFeeDate(Date feeDate)
	{
		this.feeDate = feeDate;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getAccountNo()
	{
		return this.accountNo;
	}

	public void setAccountNo(String accountNo)
	{
		this.accountNo = accountNo;
	}

	public BigDecimal getAmount()
	{
		return this.amount;
	}

	public void setAmount(BigDecimal amount)
	{
		this.amount = amount;
	}

	public Character getFeeType()
	{
		return this.feeType;
	}

	public void setFeeType(Character feeType)
	{
		this.feeType = feeType;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public String getFeeName()
	{
		return this.feeName;
	}

	public void setFeeName(String feeName)
	{
		this.feeName = feeName;
	}

	public String getUseInfo()
	{
		return this.useInfo;
	}

	public void setUseInfo(String useInfo)
	{
		this.useInfo = useInfo;
	}

	public BigDecimal getBackAmount()
	{
		return this.backAmount;
	}

	public void setBackAmount(BigDecimal backAmount)
	{
		this.backAmount = backAmount;
	}

	public String getSeqNo()
	{
		return this.seqNo;
	}

	public void setSeqNo(String seqNo)
	{
		this.seqNo = seqNo;
	}

}
