package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FileCategory generated by hbm2java
 */
public class FileCategory implements java.io.Serializable
{

	private int id;
	private String name;
	private String remark;
	private String recordName;
	private Date recordTime;
	private Set<Files> fileses = new HashSet<Files>(0);

	public FileCategory()
	{
	}

	public FileCategory(int id, String name)
	{
		this.id = id;
		this.name = name;
	}

	public FileCategory(int id, String name, String remark, String recordName, Date recordTime, Set<Files> fileses)
	{
		this.id = id;
		this.name = name;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
		this.fileses = fileses;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public Set<Files> getFileses()
	{
		return this.fileses;
	}

	public void setFileses(Set<Files> fileses)
	{
		this.fileses = fileses;
	}

}
