package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * HlaPcr generated by hbm2java
 */
public class HlaPcr implements java.io.Serializable
{

	private int id;
	private Date operDate;
	private String pcrPos;
	private String pcrProg;
	private String pcrEquip;
	private char operType;
	private Character rcsId;
	private Integer templateId;
	private String boardNo;
	private Integer reactionSetupId;
	private Integer multiple;
	private Integer multipleA;
	private Integer multipleB;
	private Integer multipleC;
	private Integer multipleDr;
	private Integer multipleDq;
	private Integer reactionProgId;
	private Character lowId;
	private Character doubleId;
	private String operName;
	private String checkName;
	private Date checkDate;
	private String remark;
	private Date recordTime;
	private String recordName;
	private Character labId;
	private Integer multipleDpb1;

	public HlaPcr()
	{
	}

	public HlaPcr(int id, Date operDate, char operType, String operName)
	{
		this.id = id;
		this.operDate = operDate;
		this.operType = operType;
		this.operName = operName;
	}

	public HlaPcr(int id, Date operDate, String pcrPos, String pcrProg, String pcrEquip, char operType, Character rcsId,
			Integer templateId, String boardNo, Integer reactionSetupId, Integer multiple, Integer multipleA,
			Integer multipleB, Integer multipleC, Integer multipleDr, Integer multipleDq, Integer reactionProgId,
			Character lowId, Character doubleId, String operName, String checkName, Date checkDate, String remark,
			Date recordTime, String recordName, Character labId, Integer multipleDpb1)
	{
		this.id = id;
		this.operDate = operDate;
		this.pcrPos = pcrPos;
		this.pcrProg = pcrProg;
		this.pcrEquip = pcrEquip;
		this.operType = operType;
		this.rcsId = rcsId;
		this.templateId = templateId;
		this.boardNo = boardNo;
		this.reactionSetupId = reactionSetupId;
		this.multiple = multiple;
		this.multipleA = multipleA;
		this.multipleB = multipleB;
		this.multipleC = multipleC;
		this.multipleDr = multipleDr;
		this.multipleDq = multipleDq;
		this.reactionProgId = reactionProgId;
		this.lowId = lowId;
		this.doubleId = doubleId;
		this.operName = operName;
		this.checkName = checkName;
		this.checkDate = checkDate;
		this.remark = remark;
		this.recordTime = recordTime;
		this.recordName = recordName;
		this.labId = labId;
		this.multipleDpb1 = multipleDpb1;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Date getOperDate()
	{
		return this.operDate;
	}

	public void setOperDate(Date operDate)
	{
		this.operDate = operDate;
	}

	public String getPcrPos()
	{
		return this.pcrPos;
	}

	public void setPcrPos(String pcrPos)
	{
		this.pcrPos = pcrPos;
	}

	public String getPcrProg()
	{
		return this.pcrProg;
	}

	public void setPcrProg(String pcrProg)
	{
		this.pcrProg = pcrProg;
	}

	public String getPcrEquip()
	{
		return this.pcrEquip;
	}

	public void setPcrEquip(String pcrEquip)
	{
		this.pcrEquip = pcrEquip;
	}

	public char getOperType()
	{
		return this.operType;
	}

	public void setOperType(char operType)
	{
		this.operType = operType;
	}

	public Character getRcsId()
	{
		return this.rcsId;
	}

	public void setRcsId(Character rcsId)
	{
		this.rcsId = rcsId;
	}

	public Integer getTemplateId()
	{
		return this.templateId;
	}

	public void setTemplateId(Integer templateId)
	{
		this.templateId = templateId;
	}

	public String getBoardNo()
	{
		return this.boardNo;
	}

	public void setBoardNo(String boardNo)
	{
		this.boardNo = boardNo;
	}

	public Integer getReactionSetupId()
	{
		return this.reactionSetupId;
	}

	public void setReactionSetupId(Integer reactionSetupId)
	{
		this.reactionSetupId = reactionSetupId;
	}

	public Integer getMultiple()
	{
		return this.multiple;
	}

	public void setMultiple(Integer multiple)
	{
		this.multiple = multiple;
	}

	public Integer getMultipleA()
	{
		return this.multipleA;
	}

	public void setMultipleA(Integer multipleA)
	{
		this.multipleA = multipleA;
	}

	public Integer getMultipleB()
	{
		return this.multipleB;
	}

	public void setMultipleB(Integer multipleB)
	{
		this.multipleB = multipleB;
	}

	public Integer getMultipleC()
	{
		return this.multipleC;
	}

	public void setMultipleC(Integer multipleC)
	{
		this.multipleC = multipleC;
	}

	public Integer getMultipleDr()
	{
		return this.multipleDr;
	}

	public void setMultipleDr(Integer multipleDr)
	{
		this.multipleDr = multipleDr;
	}

	public Integer getMultipleDq()
	{
		return this.multipleDq;
	}

	public void setMultipleDq(Integer multipleDq)
	{
		this.multipleDq = multipleDq;
	}

	public Integer getReactionProgId()
	{
		return this.reactionProgId;
	}

	public void setReactionProgId(Integer reactionProgId)
	{
		this.reactionProgId = reactionProgId;
	}

	public Character getLowId()
	{
		return this.lowId;
	}

	public void setLowId(Character lowId)
	{
		this.lowId = lowId;
	}

	public Character getDoubleId()
	{
		return this.doubleId;
	}

	public void setDoubleId(Character doubleId)
	{
		this.doubleId = doubleId;
	}

	public String getOperName()
	{
		return this.operName;
	}

	public void setOperName(String operName)
	{
		this.operName = operName;
	}

	public String getCheckName()
	{
		return this.checkName;
	}

	public void setCheckName(String checkName)
	{
		this.checkName = checkName;
	}

	public Date getCheckDate()
	{
		return this.checkDate;
	}

	public void setCheckDate(Date checkDate)
	{
		this.checkDate = checkDate;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Character getLabId()
	{
		return this.labId;
	}

	public void setLabId(Character labId)
	{
		this.labId = labId;
	}

	public Integer getMultipleDpb1()
	{
		return this.multipleDpb1;
	}

	public void setMultipleDpb1(Integer multipleDpb1)
	{
		this.multipleDpb1 = multipleDpb1;
	}

}
