package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

/**
 * HlaSsop generated by hbm2java
 */
public class HlaSsop implements java.io.Serializable
{

	private HlaSsopId id;

	public HlaSsop()
	{
	}

	public HlaSsop(HlaSsopId id)
	{
		this.id = id;
	}

	public HlaSsopId getId()
	{
		return this.id;
	}

	public void setId(HlaSsopId id)
	{
		this.id = id;
	}

}
