package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * HlaSsopId generated by hbm2java
 */
public class HlaSsopId implements java.io.Serializable
{

	private int id;
	private String sampleNo;
	private String point;
	private String allelePairs;
	private String imgtVersion;
	private int useFlag;
	private Date recordTime;
	private String recordName;
	private String replaceNo;

	public HlaSsopId()
	{
	}

	public HlaSsopId(int id, int useFlag)
	{
		this.id = id;
		this.useFlag = useFlag;
	}

	public HlaSsopId(int id, String sampleNo, String point, String allelePairs, String imgtVersion, int useFlag,
			Date recordTime, String recordName, String replaceNo)
	{
		this.id = id;
		this.sampleNo = sampleNo;
		this.point = point;
		this.allelePairs = allelePairs;
		this.imgtVersion = imgtVersion;
		this.useFlag = useFlag;
		this.recordTime = recordTime;
		this.recordName = recordName;
		this.replaceNo = replaceNo;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getSampleNo()
	{
		return this.sampleNo;
	}

	public void setSampleNo(String sampleNo)
	{
		this.sampleNo = sampleNo;
	}

	public String getPoint()
	{
		return this.point;
	}

	public void setPoint(String point)
	{
		this.point = point;
	}

	public String getAllelePairs()
	{
		return this.allelePairs;
	}

	public void setAllelePairs(String allelePairs)
	{
		this.allelePairs = allelePairs;
	}

	public String getImgtVersion()
	{
		return this.imgtVersion;
	}

	public void setImgtVersion(String imgtVersion)
	{
		this.imgtVersion = imgtVersion;
	}

	public int getUseFlag()
	{
		return this.useFlag;
	}

	public void setUseFlag(int useFlag)
	{
		this.useFlag = useFlag;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public String getReplaceNo()
	{
		return this.replaceNo;
	}

	public void setReplaceNo(String replaceNo)
	{
		this.replaceNo = replaceNo;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HlaSsopId))
			return false;
		HlaSsopId castOther = (HlaSsopId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getSampleNo() == castOther.getSampleNo()) || (this.getSampleNo() != null
						&& castOther.getSampleNo() != null && this.getSampleNo().equals(castOther.getSampleNo())))
				&& ((this.getPoint() == castOther.getPoint()) || (this.getPoint() != null
						&& castOther.getPoint() != null && this.getPoint().equals(castOther.getPoint())))
				&& ((this.getAllelePairs() == castOther.getAllelePairs())
						|| (this.getAllelePairs() != null && castOther.getAllelePairs() != null
								&& this.getAllelePairs().equals(castOther.getAllelePairs())))
				&& ((this.getImgtVersion() == castOther.getImgtVersion())
						|| (this.getImgtVersion() != null && castOther.getImgtVersion() != null
								&& this.getImgtVersion().equals(castOther.getImgtVersion())))
				&& (this.getUseFlag() == castOther.getUseFlag())
				&& ((this.getRecordTime() == castOther.getRecordTime()) || (this.getRecordTime() != null
						&& castOther.getRecordTime() != null && this.getRecordTime().equals(castOther.getRecordTime())))
				&& ((this.getRecordName() == castOther.getRecordName()) || (this.getRecordName() != null
						&& castOther.getRecordName() != null && this.getRecordName().equals(castOther.getRecordName())))
				&& ((this.getReplaceNo() == castOther.getReplaceNo()) || (this.getReplaceNo() != null
						&& castOther.getReplaceNo() != null && this.getReplaceNo().equals(castOther.getReplaceNo())));
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getSampleNo() == null ? 0 : this.getSampleNo().hashCode());
		result = 37 * result + (getPoint() == null ? 0 : this.getPoint().hashCode());
		result = 37 * result + (getAllelePairs() == null ? 0 : this.getAllelePairs().hashCode());
		result = 37 * result + (getImgtVersion() == null ? 0 : this.getImgtVersion().hashCode());
		result = 37 * result + this.getUseFlag();
		result = 37 * result + (getRecordTime() == null ? 0 : this.getRecordTime().hashCode());
		result = 37 * result + (getRecordName() == null ? 0 : this.getRecordName().hashCode());
		result = 37 * result + (getReplaceNo() == null ? 0 : this.getReplaceNo().hashCode());
		return result;
	}

}
