package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * LiquidSterilize generated by hbm2java
 */
public class LiquidSterilize implements java.io.Serializable
{

	private int id;
	private Date liquidDate;
	private int num;
	private String batchNo;
	private Integer addNum;
	private Integer times;
	private char clId;
	private String operator;
	private String remark;
	private String recordName;
	private Date recordTime;

	public LiquidSterilize()
	{
	}

	public LiquidSterilize(int id, Date liquidDate, int num, char clId)
	{
		this.id = id;
		this.liquidDate = liquidDate;
		this.num = num;
		this.clId = clId;
	}

	public LiquidSterilize(int id, Date liquidDate, int num, String batchNo, Integer addNum, Integer times, char clId,
			String operator, String remark, String recordName, Date recordTime)
	{
		this.id = id;
		this.liquidDate = liquidDate;
		this.num = num;
		this.batchNo = batchNo;
		this.addNum = addNum;
		this.times = times;
		this.clId = clId;
		this.operator = operator;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Date getLiquidDate()
	{
		return this.liquidDate;
	}

	public void setLiquidDate(Date liquidDate)
	{
		this.liquidDate = liquidDate;
	}

	public int getNum()
	{
		return this.num;
	}

	public void setNum(int num)
	{
		this.num = num;
	}

	public String getBatchNo()
	{
		return this.batchNo;
	}

	public void setBatchNo(String batchNo)
	{
		this.batchNo = batchNo;
	}

	public Integer getAddNum()
	{
		return this.addNum;
	}

	public void setAddNum(Integer addNum)
	{
		this.addNum = addNum;
	}

	public Integer getTimes()
	{
		return this.times;
	}

	public void setTimes(Integer times)
	{
		this.times = times;
	}

	public char getClId()
	{
		return this.clId;
	}

	public void setClId(char clId)
	{
		this.clId = clId;
	}

	public String getOperator()
	{
		return this.operator;
	}

	public void setOperator(String operator)
	{
		this.operator = operator;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

}
