package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * PaperRec generated by hbm2java
 */
public class PaperRec implements java.io.Serializable
{

	private int id;
	private Date addDate;
	private String addMan;
	private Integer nums;

	public PaperRec()
	{
	}

	public PaperRec(int id)
	{
		this.id = id;
	}

	public PaperRec(int id, Date addDate, String addMan, Integer nums)
	{
		this.id = id;
		this.addDate = addDate;
		this.addMan = addMan;
		this.nums = nums;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Date getAddDate()
	{
		return this.addDate;
	}

	public void setAddDate(Date addDate)
	{
		this.addDate = addDate;
	}

	public String getAddMan()
	{
		return this.addMan;
	}

	public void setAddMan(String addMan)
	{
		this.addMan = addMan;
	}

	public Integer getNums()
	{
		return this.nums;
	}

	public void setNums(Integer nums)
	{
		this.nums = nums;
	}

}
