package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * Pbcatcol generated by hbm2java
 */
public class Pbcatcol implements java.io.Serializable
{

	private PbcatcolId id;

	public Pbcatcol()
	{
	}

	public Pbcatcol(PbcatcolId id)
	{
		this.id = id;
	}

	public PbcatcolId getId()
	{
		return this.id;
	}

	public void setId(PbcatcolId id)
	{
		this.id = id;
	}

}
