package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * PbcattblId generated by hbm2java
 */
public class PbcattblId implements java.io.Serializable
{

	private String pbtTnam;
	private Integer pbtTid;
	private String pbtOwnr;
	private Short pbdFhgt;
	private Short pbdFwgt;
	private Character pbdFitl;
	private Character pbdFunl;
	private Short pbdFchr;
	private Short pbdFptc;
	private String pbdFfce;
	private Short pbhFhgt;
	private Short pbhFwgt;
	private Character pbhFitl;
	private Character pbhFunl;
	private Short pbhFchr;
	private Short pbhFptc;
	private String pbhFfce;
	private Short pblFhgt;
	private Short pblFwgt;
	private Character pblFitl;
	private Character pblFunl;
	private Short pblFchr;
	private Short pblFptc;
	private String pblFfce;
	private String pbtCmnt;

	public PbcattblId()
	{
	}

	public PbcattblId(String pbtTnam, Integer pbtTid, String pbtOwnr, Short pbdFhgt, Short pbdFwgt, Character pbdFitl,
			Character pbdFunl, Short pbdFchr, Short pbdFptc, String pbdFfce, Short pbhFhgt, Short pbhFwgt,
			Character pbhFitl, Character pbhFunl, Short pbhFchr, Short pbhFptc, String pbhFfce, Short pblFhgt,
			Short pblFwgt, Character pblFitl, Character pblFunl, Short pblFchr, Short pblFptc, String pblFfce,
			String pbtCmnt)
	{
		this.pbtTnam = pbtTnam;
		this.pbtTid = pbtTid;
		this.pbtOwnr = pbtOwnr;
		this.pbdFhgt = pbdFhgt;
		this.pbdFwgt = pbdFwgt;
		this.pbdFitl = pbdFitl;
		this.pbdFunl = pbdFunl;
		this.pbdFchr = pbdFchr;
		this.pbdFptc = pbdFptc;
		this.pbdFfce = pbdFfce;
		this.pbhFhgt = pbhFhgt;
		this.pbhFwgt = pbhFwgt;
		this.pbhFitl = pbhFitl;
		this.pbhFunl = pbhFunl;
		this.pbhFchr = pbhFchr;
		this.pbhFptc = pbhFptc;
		this.pbhFfce = pbhFfce;
		this.pblFhgt = pblFhgt;
		this.pblFwgt = pblFwgt;
		this.pblFitl = pblFitl;
		this.pblFunl = pblFunl;
		this.pblFchr = pblFchr;
		this.pblFptc = pblFptc;
		this.pblFfce = pblFfce;
		this.pbtCmnt = pbtCmnt;
	}

	public String getPbtTnam()
	{
		return this.pbtTnam;
	}

	public void setPbtTnam(String pbtTnam)
	{
		this.pbtTnam = pbtTnam;
	}

	public Integer getPbtTid()
	{
		return this.pbtTid;
	}

	public void setPbtTid(Integer pbtTid)
	{
		this.pbtTid = pbtTid;
	}

	public String getPbtOwnr()
	{
		return this.pbtOwnr;
	}

	public void setPbtOwnr(String pbtOwnr)
	{
		this.pbtOwnr = pbtOwnr;
	}

	public Short getPbdFhgt()
	{
		return this.pbdFhgt;
	}

	public void setPbdFhgt(Short pbdFhgt)
	{
		this.pbdFhgt = pbdFhgt;
	}

	public Short getPbdFwgt()
	{
		return this.pbdFwgt;
	}

	public void setPbdFwgt(Short pbdFwgt)
	{
		this.pbdFwgt = pbdFwgt;
	}

	public Character getPbdFitl()
	{
		return this.pbdFitl;
	}

	public void setPbdFitl(Character pbdFitl)
	{
		this.pbdFitl = pbdFitl;
	}

	public Character getPbdFunl()
	{
		return this.pbdFunl;
	}

	public void setPbdFunl(Character pbdFunl)
	{
		this.pbdFunl = pbdFunl;
	}

	public Short getPbdFchr()
	{
		return this.pbdFchr;
	}

	public void setPbdFchr(Short pbdFchr)
	{
		this.pbdFchr = pbdFchr;
	}

	public Short getPbdFptc()
	{
		return this.pbdFptc;
	}

	public void setPbdFptc(Short pbdFptc)
	{
		this.pbdFptc = pbdFptc;
	}

	public String getPbdFfce()
	{
		return this.pbdFfce;
	}

	public void setPbdFfce(String pbdFfce)
	{
		this.pbdFfce = pbdFfce;
	}

	public Short getPbhFhgt()
	{
		return this.pbhFhgt;
	}

	public void setPbhFhgt(Short pbhFhgt)
	{
		this.pbhFhgt = pbhFhgt;
	}

	public Short getPbhFwgt()
	{
		return this.pbhFwgt;
	}

	public void setPbhFwgt(Short pbhFwgt)
	{
		this.pbhFwgt = pbhFwgt;
	}

	public Character getPbhFitl()
	{
		return this.pbhFitl;
	}

	public void setPbhFitl(Character pbhFitl)
	{
		this.pbhFitl = pbhFitl;
	}

	public Character getPbhFunl()
	{
		return this.pbhFunl;
	}

	public void setPbhFunl(Character pbhFunl)
	{
		this.pbhFunl = pbhFunl;
	}

	public Short getPbhFchr()
	{
		return this.pbhFchr;
	}

	public void setPbhFchr(Short pbhFchr)
	{
		this.pbhFchr = pbhFchr;
	}

	public Short getPbhFptc()
	{
		return this.pbhFptc;
	}

	public void setPbhFptc(Short pbhFptc)
	{
		this.pbhFptc = pbhFptc;
	}

	public String getPbhFfce()
	{
		return this.pbhFfce;
	}

	public void setPbhFfce(String pbhFfce)
	{
		this.pbhFfce = pbhFfce;
	}

	public Short getPblFhgt()
	{
		return this.pblFhgt;
	}

	public void setPblFhgt(Short pblFhgt)
	{
		this.pblFhgt = pblFhgt;
	}

	public Short getPblFwgt()
	{
		return this.pblFwgt;
	}

	public void setPblFwgt(Short pblFwgt)
	{
		this.pblFwgt = pblFwgt;
	}

	public Character getPblFitl()
	{
		return this.pblFitl;
	}

	public void setPblFitl(Character pblFitl)
	{
		this.pblFitl = pblFitl;
	}

	public Character getPblFunl()
	{
		return this.pblFunl;
	}

	public void setPblFunl(Character pblFunl)
	{
		this.pblFunl = pblFunl;
	}

	public Short getPblFchr()
	{
		return this.pblFchr;
	}

	public void setPblFchr(Short pblFchr)
	{
		this.pblFchr = pblFchr;
	}

	public Short getPblFptc()
	{
		return this.pblFptc;
	}

	public void setPblFptc(Short pblFptc)
	{
		this.pblFptc = pblFptc;
	}

	public String getPblFfce()
	{
		return this.pblFfce;
	}

	public void setPblFfce(String pblFfce)
	{
		this.pblFfce = pblFfce;
	}

	public String getPbtCmnt()
	{
		return this.pbtCmnt;
	}

	public void setPbtCmnt(String pbtCmnt)
	{
		this.pbtCmnt = pbtCmnt;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PbcattblId))
			return false;
		PbcattblId castOther = (PbcattblId) other;

		return ((this.getPbtTnam() == castOther.getPbtTnam()) || (this.getPbtTnam() != null
				&& castOther.getPbtTnam() != null && this.getPbtTnam().equals(castOther.getPbtTnam())))
				&& ((this.getPbtTid() == castOther.getPbtTid()) || (this.getPbtTid() != null
						&& castOther.getPbtTid() != null && this.getPbtTid().equals(castOther.getPbtTid())))
				&& ((this.getPbtOwnr() == castOther.getPbtOwnr()) || (this.getPbtOwnr() != null
						&& castOther.getPbtOwnr() != null && this.getPbtOwnr().equals(castOther.getPbtOwnr())))
				&& ((this.getPbdFhgt() == castOther.getPbdFhgt()) || (this.getPbdFhgt() != null
						&& castOther.getPbdFhgt() != null && this.getPbdFhgt().equals(castOther.getPbdFhgt())))
				&& ((this.getPbdFwgt() == castOther.getPbdFwgt()) || (this.getPbdFwgt() != null
						&& castOther.getPbdFwgt() != null && this.getPbdFwgt().equals(castOther.getPbdFwgt())))
				&& ((this.getPbdFitl() == castOther.getPbdFitl()) || (this.getPbdFitl() != null
						&& castOther.getPbdFitl() != null && this.getPbdFitl().equals(castOther.getPbdFitl())))
				&& ((this.getPbdFunl() == castOther.getPbdFunl()) || (this.getPbdFunl() != null
						&& castOther.getPbdFunl() != null && this.getPbdFunl().equals(castOther.getPbdFunl())))
				&& ((this.getPbdFchr() == castOther.getPbdFchr()) || (this.getPbdFchr() != null
						&& castOther.getPbdFchr() != null && this.getPbdFchr().equals(castOther.getPbdFchr())))
				&& ((this.getPbdFptc() == castOther.getPbdFptc()) || (this.getPbdFptc() != null
						&& castOther.getPbdFptc() != null && this.getPbdFptc().equals(castOther.getPbdFptc())))
				&& ((this.getPbdFfce() == castOther.getPbdFfce()) || (this.getPbdFfce() != null
						&& castOther.getPbdFfce() != null && this.getPbdFfce().equals(castOther.getPbdFfce())))
				&& ((this.getPbhFhgt() == castOther.getPbhFhgt()) || (this.getPbhFhgt() != null
						&& castOther.getPbhFhgt() != null && this.getPbhFhgt().equals(castOther.getPbhFhgt())))
				&& ((this.getPbhFwgt() == castOther.getPbhFwgt()) || (this.getPbhFwgt() != null
						&& castOther.getPbhFwgt() != null && this.getPbhFwgt().equals(castOther.getPbhFwgt())))
				&& ((this.getPbhFitl() == castOther.getPbhFitl()) || (this.getPbhFitl() != null
						&& castOther.getPbhFitl() != null && this.getPbhFitl().equals(castOther.getPbhFitl())))
				&& ((this.getPbhFunl() == castOther.getPbhFunl()) || (this.getPbhFunl() != null
						&& castOther.getPbhFunl() != null && this.getPbhFunl().equals(castOther.getPbhFunl())))
				&& ((this.getPbhFchr() == castOther.getPbhFchr()) || (this.getPbhFchr() != null
						&& castOther.getPbhFchr() != null && this.getPbhFchr().equals(castOther.getPbhFchr())))
				&& ((this.getPbhFptc() == castOther.getPbhFptc()) || (this.getPbhFptc() != null
						&& castOther.getPbhFptc() != null && this.getPbhFptc().equals(castOther.getPbhFptc())))
				&& ((this.getPbhFfce() == castOther.getPbhFfce()) || (this.getPbhFfce() != null
						&& castOther.getPbhFfce() != null && this.getPbhFfce().equals(castOther.getPbhFfce())))
				&& ((this.getPblFhgt() == castOther.getPblFhgt()) || (this.getPblFhgt() != null
						&& castOther.getPblFhgt() != null && this.getPblFhgt().equals(castOther.getPblFhgt())))
				&& ((this.getPblFwgt() == castOther.getPblFwgt()) || (this.getPblFwgt() != null
						&& castOther.getPblFwgt() != null && this.getPblFwgt().equals(castOther.getPblFwgt())))
				&& ((this.getPblFitl() == castOther.getPblFitl()) || (this.getPblFitl() != null
						&& castOther.getPblFitl() != null && this.getPblFitl().equals(castOther.getPblFitl())))
				&& ((this.getPblFunl() == castOther.getPblFunl()) || (this.getPblFunl() != null
						&& castOther.getPblFunl() != null && this.getPblFunl().equals(castOther.getPblFunl())))
				&& ((this.getPblFchr() == castOther.getPblFchr()) || (this.getPblFchr() != null
						&& castOther.getPblFchr() != null && this.getPblFchr().equals(castOther.getPblFchr())))
				&& ((this.getPblFptc() == castOther.getPblFptc()) || (this.getPblFptc() != null
						&& castOther.getPblFptc() != null && this.getPblFptc().equals(castOther.getPblFptc())))
				&& ((this.getPblFfce() == castOther.getPblFfce()) || (this.getPblFfce() != null
						&& castOther.getPblFfce() != null && this.getPblFfce().equals(castOther.getPblFfce())))
				&& ((this.getPbtCmnt() == castOther.getPbtCmnt()) || (this.getPbtCmnt() != null
						&& castOther.getPbtCmnt() != null && this.getPbtCmnt().equals(castOther.getPbtCmnt())));
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result + (getPbtTnam() == null ? 0 : this.getPbtTnam().hashCode());
		result = 37 * result + (getPbtTid() == null ? 0 : this.getPbtTid().hashCode());
		result = 37 * result + (getPbtOwnr() == null ? 0 : this.getPbtOwnr().hashCode());
		result = 37 * result + (getPbdFhgt() == null ? 0 : this.getPbdFhgt().hashCode());
		result = 37 * result + (getPbdFwgt() == null ? 0 : this.getPbdFwgt().hashCode());
		result = 37 * result + (getPbdFitl() == null ? 0 : this.getPbdFitl().hashCode());
		result = 37 * result + (getPbdFunl() == null ? 0 : this.getPbdFunl().hashCode());
		result = 37 * result + (getPbdFchr() == null ? 0 : this.getPbdFchr().hashCode());
		result = 37 * result + (getPbdFptc() == null ? 0 : this.getPbdFptc().hashCode());
		result = 37 * result + (getPbdFfce() == null ? 0 : this.getPbdFfce().hashCode());
		result = 37 * result + (getPbhFhgt() == null ? 0 : this.getPbhFhgt().hashCode());
		result = 37 * result + (getPbhFwgt() == null ? 0 : this.getPbhFwgt().hashCode());
		result = 37 * result + (getPbhFitl() == null ? 0 : this.getPbhFitl().hashCode());
		result = 37 * result + (getPbhFunl() == null ? 0 : this.getPbhFunl().hashCode());
		result = 37 * result + (getPbhFchr() == null ? 0 : this.getPbhFchr().hashCode());
		result = 37 * result + (getPbhFptc() == null ? 0 : this.getPbhFptc().hashCode());
		result = 37 * result + (getPbhFfce() == null ? 0 : this.getPbhFfce().hashCode());
		result = 37 * result + (getPblFhgt() == null ? 0 : this.getPblFhgt().hashCode());
		result = 37 * result + (getPblFwgt() == null ? 0 : this.getPblFwgt().hashCode());
		result = 37 * result + (getPblFitl() == null ? 0 : this.getPblFitl().hashCode());
		result = 37 * result + (getPblFunl() == null ? 0 : this.getPblFunl().hashCode());
		result = 37 * result + (getPblFchr() == null ? 0 : this.getPblFchr().hashCode());
		result = 37 * result + (getPblFptc() == null ? 0 : this.getPblFptc().hashCode());
		result = 37 * result + (getPblFfce() == null ? 0 : this.getPblFfce().hashCode());
		result = 37 * result + (getPbtCmnt() == null ? 0 : this.getPbtCmnt().hashCode());
		return result;
	}

}
