package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * Pbcatfmt generated by hbm2java
 */
public class Pbcatfmt implements java.io.Serializable
{

	private PbcatfmtId id;

	public Pbcatfmt()
	{
	}

	public Pbcatfmt(PbcatfmtId id)
	{
		this.id = id;
	}

	public PbcatfmtId getId()
	{
		return this.id;
	}

	public void setId(PbcatfmtId id)
	{
		this.id = id;
	}

}
