package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

/**
 * Pbcattbl generated by hbm2java
 */
public class Pbcattbl implements java.io.Serializable
{

	private PbcattblId id;

	public Pbcattbl()
	{
	}

	public Pbcattbl(PbcattblId id)
	{
		this.id = id;
	}

	public PbcattblId getId()
	{
		return this.id;
	}

	public void setId(PbcattblId id)
	{
		this.id = id;
	}

}
