package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ReactionTableRecord generated by hbm2java
 */
public class ReactionTableRecord implements java.io.Serializable
{

	private int id;
	private CheckBill checkBill;
	private Integer reagentId;
	private String reagentName;
	private Integer batchId;
	private String batchNo;
	private String method;
	private String res1;
	private String res2;
	private String res3;
	private String res4;
	private String res5;
	private String res6;
	private String res7;
	private String res8;
	private String res9;
	private String res10;
	private String res11;
	private String result;
	private char reportRes;
	private String remark;
	private String recordName;
	private Date recordTime;
	private String res12;
	private String res13;
	private String res14;
	private String res15;
	private String res16;
	private Character item;
	private String sampleNo;

	public ReactionTableRecord()
	{
	}

	public ReactionTableRecord(int id, CheckBill checkBill, char reportRes)
	{
		this.id = id;
		this.checkBill = checkBill;
		this.reportRes = reportRes;
	}

	public ReactionTableRecord(int id, CheckBill checkBill, Integer reagentId, String reagentName, Integer batchId,
			String batchNo, String method, String res1, String res2, String res3, String res4, String res5, String res6,
			String res7, String res8, String res9, String res10, String res11, String result, char reportRes,
			String remark, String recordName, Date recordTime, String res12, String res13, String res14, String res15,
			String res16, Character item, String sampleNo)
	{
		this.id = id;
		this.checkBill = checkBill;
		this.reagentId = reagentId;
		this.reagentName = reagentName;
		this.batchId = batchId;
		this.batchNo = batchNo;
		this.method = method;
		this.res1 = res1;
		this.res2 = res2;
		this.res3 = res3;
		this.res4 = res4;
		this.res5 = res5;
		this.res6 = res6;
		this.res7 = res7;
		this.res8 = res8;
		this.res9 = res9;
		this.res10 = res10;
		this.res11 = res11;
		this.result = result;
		this.reportRes = reportRes;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
		this.res12 = res12;
		this.res13 = res13;
		this.res14 = res14;
		this.res15 = res15;
		this.res16 = res16;
		this.item = item;
		this.sampleNo = sampleNo;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public CheckBill getCheckBill()
	{
		return this.checkBill;
	}

	public void setCheckBill(CheckBill checkBill)
	{
		this.checkBill = checkBill;
	}

	public Integer getReagentId()
	{
		return this.reagentId;
	}

	public void setReagentId(Integer reagentId)
	{
		this.reagentId = reagentId;
	}

	public String getReagentName()
	{
		return this.reagentName;
	}

	public void setReagentName(String reagentName)
	{
		this.reagentName = reagentName;
	}

	public Integer getBatchId()
	{
		return this.batchId;
	}

	public void setBatchId(Integer batchId)
	{
		this.batchId = batchId;
	}

	public String getBatchNo()
	{
		return this.batchNo;
	}

	public void setBatchNo(String batchNo)
	{
		this.batchNo = batchNo;
	}

	public String getMethod()
	{
		return this.method;
	}

	public void setMethod(String method)
	{
		this.method = method;
	}

	public String getRes1()
	{
		return this.res1;
	}

	public void setRes1(String res1)
	{
		this.res1 = res1;
	}

	public String getRes2()
	{
		return this.res2;
	}

	public void setRes2(String res2)
	{
		this.res2 = res2;
	}

	public String getRes3()
	{
		return this.res3;
	}

	public void setRes3(String res3)
	{
		this.res3 = res3;
	}

	public String getRes4()
	{
		return this.res4;
	}

	public void setRes4(String res4)
	{
		this.res4 = res4;
	}

	public String getRes5()
	{
		return this.res5;
	}

	public void setRes5(String res5)
	{
		this.res5 = res5;
	}

	public String getRes6()
	{
		return this.res6;
	}

	public void setRes6(String res6)
	{
		this.res6 = res6;
	}

	public String getRes7()
	{
		return this.res7;
	}

	public void setRes7(String res7)
	{
		this.res7 = res7;
	}

	public String getRes8()
	{
		return this.res8;
	}

	public void setRes8(String res8)
	{
		this.res8 = res8;
	}

	public String getRes9()
	{
		return this.res9;
	}

	public void setRes9(String res9)
	{
		this.res9 = res9;
	}

	public String getRes10()
	{
		return this.res10;
	}

	public void setRes10(String res10)
	{
		this.res10 = res10;
	}

	public String getRes11()
	{
		return this.res11;
	}

	public void setRes11(String res11)
	{
		this.res11 = res11;
	}

	public String getResult()
	{
		return this.result;
	}

	public void setResult(String result)
	{
		this.result = result;
	}

	public char getReportRes()
	{
		return this.reportRes;
	}

	public void setReportRes(char reportRes)
	{
		this.reportRes = reportRes;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getRes12()
	{
		return this.res12;
	}

	public void setRes12(String res12)
	{
		this.res12 = res12;
	}

	public String getRes13()
	{
		return this.res13;
	}

	public void setRes13(String res13)
	{
		this.res13 = res13;
	}

	public String getRes14()
	{
		return this.res14;
	}

	public void setRes14(String res14)
	{
		this.res14 = res14;
	}

	public String getRes15()
	{
		return this.res15;
	}

	public void setRes15(String res15)
	{
		this.res15 = res15;
	}

	public String getRes16()
	{
		return this.res16;
	}

	public void setRes16(String res16)
	{
		this.res16 = res16;
	}

	public Character getItem()
	{
		return this.item;
	}

	public void setItem(Character item)
	{
		this.item = item;
	}

	public String getSampleNo()
	{
		return this.sampleNo;
	}

	public void setSampleNo(String sampleNo)
	{
		this.sampleNo = sampleNo;
	}

}
