package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ReagentBatch generated by hbm2java
 */
public class ReagentBatch implements java.io.Serializable
{

	private int id;
	private CReagent CReagent;
	private String reagentName;
	private String batchNo;
	private Date prodDate;
	private Date validDate;
	private String position;
	private Character status;
	private String remark;
	private String recordName;
	private Date recordTime;

	public ReagentBatch()
	{
	}

	public ReagentBatch(int id, CReagent CReagent, String reagentName, String position)
	{
		this.id = id;
		this.CReagent = CReagent;
		this.reagentName = reagentName;
		this.position = position;
	}

	public ReagentBatch(int id, CReagent CReagent, String reagentName, String batchNo, Date prodDate, Date validDate,
			String position, Character status, String remark, String recordName, Date recordTime)
	{
		this.id = id;
		this.CReagent = CReagent;
		this.reagentName = reagentName;
		this.batchNo = batchNo;
		this.prodDate = prodDate;
		this.validDate = validDate;
		this.position = position;
		this.status = status;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public CReagent getCReagent()
	{
		return this.CReagent;
	}

	public void setCReagent(CReagent CReagent)
	{
		this.CReagent = CReagent;
	}

	public String getReagentName()
	{
		return this.reagentName;
	}

	public void setReagentName(String reagentName)
	{
		this.reagentName = reagentName;
	}

	public String getBatchNo()
	{
		return this.batchNo;
	}

	public void setBatchNo(String batchNo)
	{
		this.batchNo = batchNo;
	}

	public Date getProdDate()
	{
		return this.prodDate;
	}

	public void setProdDate(Date prodDate)
	{
		this.prodDate = prodDate;
	}

	public Date getValidDate()
	{
		return this.validDate;
	}

	public void setValidDate(Date validDate)
	{
		this.validDate = validDate;
	}

	public String getPosition()
	{
		return this.position;
	}

	public void setPosition(String position)
	{
		this.position = position;
	}

	public Character getStatus()
	{
		return this.status;
	}

	public void setStatus(Character status)
	{
		this.status = status;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

}
