package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ReagentIo generated by hbm2java
 */
public class ReagentIo implements java.io.Serializable
{

	private int id;
	private Date ioDate;
	private Integer reagentId;
	private String reagentName;
	private int batchId;
	private String batchNo;
	private char ioId;
	private int num;
	private String remark;
	private String recordName;
	private Date recordTime;

	public ReagentIo()
	{
	}

	public ReagentIo(int id, Date ioDate, int batchId, char ioId, int num)
	{
		this.id = id;
		this.ioDate = ioDate;
		this.batchId = batchId;
		this.ioId = ioId;
		this.num = num;
	}

	public ReagentIo(int id, Date ioDate, Integer reagentId, String reagentName, int batchId, String batchNo, char ioId,
			int num, String remark, String recordName, Date recordTime)
	{
		this.id = id;
		this.ioDate = ioDate;
		this.reagentId = reagentId;
		this.reagentName = reagentName;
		this.batchId = batchId;
		this.batchNo = batchNo;
		this.ioId = ioId;
		this.num = num;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Date getIoDate()
	{
		return this.ioDate;
	}

	public void setIoDate(Date ioDate)
	{
		this.ioDate = ioDate;
	}

	public Integer getReagentId()
	{
		return this.reagentId;
	}

	public void setReagentId(Integer reagentId)
	{
		this.reagentId = reagentId;
	}

	public String getReagentName()
	{
		return this.reagentName;
	}

	public void setReagentName(String reagentName)
	{
		this.reagentName = reagentName;
	}

	public int getBatchId()
	{
		return this.batchId;
	}

	public void setBatchId(int batchId)
	{
		this.batchId = batchId;
	}

	public String getBatchNo()
	{
		return this.batchNo;
	}

	public void setBatchNo(String batchNo)
	{
		this.batchNo = batchNo;
	}

	public char getIoId()
	{
		return this.ioId;
	}

	public void setIoId(char ioId)
	{
		this.ioId = ioId;
	}

	public int getNum()
	{
		return this.num;
	}

	public void setNum(int num)
	{
		this.num = num;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

}
