package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ReagentTemplate generated by hbm2java
 */
public class ReagentTemplate implements java.io.Serializable
{

	private int id;
	private String name;
	private Character status;
	private String remark;
	private String recordName;
	private Date recordTime;
	private Character labId;
	private Set<ReagentTemplateDetail> reagentTemplateDetails = new HashSet<ReagentTemplateDetail>(0);

	public ReagentTemplate()
	{
	}

	public ReagentTemplate(int id, String name)
	{
		this.id = id;
		this.name = name;
	}

	public ReagentTemplate(int id, String name, Character status, String remark, String recordName, Date recordTime,
			Character labId, Set<ReagentTemplateDetail> reagentTemplateDetails)
	{
		this.id = id;
		this.name = name;
		this.status = status;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
		this.labId = labId;
		this.reagentTemplateDetails = reagentTemplateDetails;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Character getStatus()
	{
		return this.status;
	}

	public void setStatus(Character status)
	{
		this.status = status;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public Character getLabId()
	{
		return this.labId;
	}

	public void setLabId(Character labId)
	{
		this.labId = labId;
	}

	public Set<ReagentTemplateDetail> getReagentTemplateDetails()
	{
		return this.reagentTemplateDetails;
	}

	public void setReagentTemplateDetails(Set<ReagentTemplateDetail> reagentTemplateDetails)
	{
		this.reagentTemplateDetails = reagentTemplateDetails;
	}

}
