package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ResAbTiter generated by hbm2java
 */
public class ResAbTiter implements java.io.Serializable
{

	private int id;
	private CheckBill checkBill;
	private String name;
	private String abType;
	private String method;
	private String result16;
	private String result32;
	private String result64;
	private String result128;
	private String result256;
	private String result512;
	private String result1024;
	private String result;
	private String remark;
	private String recordName;
	private Date recordTime;
	private String result1;
	private String result2;
	private String result4;
	private String result8;

	public ResAbTiter()
	{
	}

	public ResAbTiter(int id, CheckBill checkBill, String name, String abType)
	{
		this.id = id;
		this.checkBill = checkBill;
		this.name = name;
		this.abType = abType;
	}

	public ResAbTiter(int id, CheckBill checkBill, String name, String abType, String method, String result16,
			String result32, String result64, String result128, String result256, String result512, String result1024,
			String result, String remark, String recordName, Date recordTime, String result1, String result2,
			String result4, String result8)
	{
		this.id = id;
		this.checkBill = checkBill;
		this.name = name;
		this.abType = abType;
		this.method = method;
		this.result16 = result16;
		this.result32 = result32;
		this.result64 = result64;
		this.result128 = result128;
		this.result256 = result256;
		this.result512 = result512;
		this.result1024 = result1024;
		this.result = result;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
		this.result1 = result1;
		this.result2 = result2;
		this.result4 = result4;
		this.result8 = result8;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public CheckBill getCheckBill()
	{
		return this.checkBill;
	}

	public void setCheckBill(CheckBill checkBill)
	{
		this.checkBill = checkBill;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getAbType()
	{
		return this.abType;
	}

	public void setAbType(String abType)
	{
		this.abType = abType;
	}

	public String getMethod()
	{
		return this.method;
	}

	public void setMethod(String method)
	{
		this.method = method;
	}

	public String getResult16()
	{
		return this.result16;
	}

	public void setResult16(String result16)
	{
		this.result16 = result16;
	}

	public String getResult32()
	{
		return this.result32;
	}

	public void setResult32(String result32)
	{
		this.result32 = result32;
	}

	public String getResult64()
	{
		return this.result64;
	}

	public void setResult64(String result64)
	{
		this.result64 = result64;
	}

	public String getResult128()
	{
		return this.result128;
	}

	public void setResult128(String result128)
	{
		this.result128 = result128;
	}

	public String getResult256()
	{
		return this.result256;
	}

	public void setResult256(String result256)
	{
		this.result256 = result256;
	}

	public String getResult512()
	{
		return this.result512;
	}

	public void setResult512(String result512)
	{
		this.result512 = result512;
	}

	public String getResult1024()
	{
		return this.result1024;
	}

	public void setResult1024(String result1024)
	{
		this.result1024 = result1024;
	}

	public String getResult()
	{
		return this.result;
	}

	public void setResult(String result)
	{
		this.result = result;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getResult1()
	{
		return this.result1;
	}

	public void setResult1(String result1)
	{
		this.result1 = result1;
	}

	public String getResult2()
	{
		return this.result2;
	}

	public void setResult2(String result2)
	{
		this.result2 = result2;
	}

	public String getResult4()
	{
		return this.result4;
	}

	public void setResult4(String result4)
	{
		this.result4 = result4;
	}

	public String getResult8()
	{
		return this.result8;
	}

	public void setResult8(String result8)
	{
		this.result8 = result8;
	}

}
