package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Sample generated by hbm2java
 */
public class Sample implements java.io.Serializable
{

	private int id;
	private CheckBill checkBill;
	private String category;
	private Date acceptDate;
	private char acceptType;
	private String no;
	private Integer num;
	private String result;
	private String reason;
	private String acceptMan;
	private String saveType;
	private Date discardDate;
	private String discardMan;
	private String discardChkMan;
	private Date recordTime;
	private String recordName;
	private String remark;

	public Sample()
	{
	}

	public Sample(int id, CheckBill checkBill, String category, Date acceptDate, char acceptType)
	{
		this.id = id;
		this.checkBill = checkBill;
		this.category = category;
		this.acceptDate = acceptDate;
		this.acceptType = acceptType;
	}

	public Sample(int id, CheckBill checkBill, String category, Date acceptDate, char acceptType, String no,
			Integer num, String result, String reason, String acceptMan, String saveType, Date discardDate,
			String discardMan, String discardChkMan, Date recordTime, String recordName, String remark)
	{
		this.id = id;
		this.checkBill = checkBill;
		this.category = category;
		this.acceptDate = acceptDate;
		this.acceptType = acceptType;
		this.no = no;
		this.num = num;
		this.result = result;
		this.reason = reason;
		this.acceptMan = acceptMan;
		this.saveType = saveType;
		this.discardDate = discardDate;
		this.discardMan = discardMan;
		this.discardChkMan = discardChkMan;
		this.recordTime = recordTime;
		this.recordName = recordName;
		this.remark = remark;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public CheckBill getCheckBill()
	{
		return this.checkBill;
	}

	public void setCheckBill(CheckBill checkBill)
	{
		this.checkBill = checkBill;
	}

	public String getCategory()
	{
		return this.category;
	}

	public void setCategory(String category)
	{
		this.category = category;
	}

	public Date getAcceptDate()
	{
		return this.acceptDate;
	}

	public void setAcceptDate(Date acceptDate)
	{
		this.acceptDate = acceptDate;
	}

	public char getAcceptType()
	{
		return this.acceptType;
	}

	public void setAcceptType(char acceptType)
	{
		this.acceptType = acceptType;
	}

	public String getNo()
	{
		return this.no;
	}

	public void setNo(String no)
	{
		this.no = no;
	}

	public Integer getNum()
	{
		return this.num;
	}

	public void setNum(Integer num)
	{
		this.num = num;
	}

	public String getResult()
	{
		return this.result;
	}

	public void setResult(String result)
	{
		this.result = result;
	}

	public String getReason()
	{
		return this.reason;
	}

	public void setReason(String reason)
	{
		this.reason = reason;
	}

	public String getAcceptMan()
	{
		return this.acceptMan;
	}

	public void setAcceptMan(String acceptMan)
	{
		this.acceptMan = acceptMan;
	}

	public String getSaveType()
	{
		return this.saveType;
	}

	public void setSaveType(String saveType)
	{
		this.saveType = saveType;
	}

	public Date getDiscardDate()
	{
		return this.discardDate;
	}

	public void setDiscardDate(Date discardDate)
	{
		this.discardDate = discardDate;
	}

	public String getDiscardMan()
	{
		return this.discardMan;
	}

	public void setDiscardMan(String discardMan)
	{
		this.discardMan = discardMan;
	}

	public String getDiscardChkMan()
	{
		return this.discardChkMan;
	}

	public void setDiscardChkMan(String discardChkMan)
	{
		this.discardChkMan = discardChkMan;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

}
