package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SampleInfo generated by hbm2java
 */
public class SampleInfo implements java.io.Serializable
{

	private int id;
	private MatchBill matchBill;
	private String sampleNo;
	private String name;
	private String relation;
	private String providerNo;
	private Character sampleFrom;
	private String sampleMan;
	private Date sampleDate;
	private String sampleType;
	private Character markId;
	private String pipeMark;
	private Character clotId;
	private String hemolysisType;
	private Character fatLevel;
	private String status;
	private Integer afterNum;
	private String sampleVol;
	private String numUnit;
	private Integer nums;
	private Character feeId;
	private Character reportId;
	private String praRes1;
	private String praRes2;
	private Character okId;
	private String remark;
	private Date recordTime;
	private String recordName;
	private String yuanshibianhao;
	private String xingbie;
	private Date caiyangriqi;
	private Date shouyangriqi;
	private Date jianceriqi;
	private String shijian;
	private String jiancexiangmu;
	private Set<SamplePic> samplePics = new HashSet<SamplePic>(0);

	public SampleInfo()
	{
	}

	public SampleInfo(int id, MatchBill matchBill, String sampleNo)
	{
		this.id = id;
		this.matchBill = matchBill;
		this.sampleNo = sampleNo;
	}

	public SampleInfo(int id, MatchBill matchBill, String sampleNo, String name, String relation, String providerNo,
			Character sampleFrom, String sampleMan, Date sampleDate, String sampleType, Character markId,
			String pipeMark, Character clotId, String hemolysisType, Character fatLevel, String status,
			Integer afterNum, String sampleVol, String numUnit, Integer nums, Character feeId, Character reportId,
			String praRes1, String praRes2, Character okId, String remark, Date recordTime, String recordName,
			String yuanshibianhao, String xingbie, Date caiyangriqi, Date shouyangriqi, Date jianceriqi, String shijian,
			String jiancexiangmu, Set<SamplePic> samplePics)
	{
		this.id = id;
		this.matchBill = matchBill;
		this.sampleNo = sampleNo;
		this.name = name;
		this.relation = relation;
		this.providerNo = providerNo;
		this.sampleFrom = sampleFrom;
		this.sampleMan = sampleMan;
		this.sampleDate = sampleDate;
		this.sampleType = sampleType;
		this.markId = markId;
		this.pipeMark = pipeMark;
		this.clotId = clotId;
		this.hemolysisType = hemolysisType;
		this.fatLevel = fatLevel;
		this.status = status;
		this.afterNum = afterNum;
		this.sampleVol = sampleVol;
		this.numUnit = numUnit;
		this.nums = nums;
		this.feeId = feeId;
		this.reportId = reportId;
		this.praRes1 = praRes1;
		this.praRes2 = praRes2;
		this.okId = okId;
		this.remark = remark;
		this.recordTime = recordTime;
		this.recordName = recordName;
		this.yuanshibianhao = yuanshibianhao;
		this.xingbie = xingbie;
		this.caiyangriqi = caiyangriqi;
		this.shouyangriqi = shouyangriqi;
		this.jianceriqi = jianceriqi;
		this.shijian = shijian;
		this.jiancexiangmu = jiancexiangmu;
		this.samplePics = samplePics;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public MatchBill getMatchBill()
	{
		return this.matchBill;
	}

	public void setMatchBill(MatchBill matchBill)
	{
		this.matchBill = matchBill;
	}

	public String getSampleNo()
	{
		return this.sampleNo;
	}

	public void setSampleNo(String sampleNo)
	{
		this.sampleNo = sampleNo;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getRelation()
	{
		return this.relation;
	}

	public void setRelation(String relation)
	{
		this.relation = relation;
	}

	public String getProviderNo()
	{
		return this.providerNo;
	}

	public void setProviderNo(String providerNo)
	{
		this.providerNo = providerNo;
	}

	public Character getSampleFrom()
	{
		return this.sampleFrom;
	}

	public void setSampleFrom(Character sampleFrom)
	{
		this.sampleFrom = sampleFrom;
	}

	public String getSampleMan()
	{
		return this.sampleMan;
	}

	public void setSampleMan(String sampleMan)
	{
		this.sampleMan = sampleMan;
	}

	public Date getSampleDate()
	{
		return this.sampleDate;
	}

	public void setSampleDate(Date sampleDate)
	{
		this.sampleDate = sampleDate;
	}

	public String getSampleType()
	{
		return this.sampleType;
	}

	public void setSampleType(String sampleType)
	{
		this.sampleType = sampleType;
	}

	public Character getMarkId()
	{
		return this.markId;
	}

	public void setMarkId(Character markId)
	{
		this.markId = markId;
	}

	public String getPipeMark()
	{
		return this.pipeMark;
	}

	public void setPipeMark(String pipeMark)
	{
		this.pipeMark = pipeMark;
	}

	public Character getClotId()
	{
		return this.clotId;
	}

	public void setClotId(Character clotId)
	{
		this.clotId = clotId;
	}

	public String getHemolysisType()
	{
		return this.hemolysisType;
	}

	public void setHemolysisType(String hemolysisType)
	{
		this.hemolysisType = hemolysisType;
	}

	public Character getFatLevel()
	{
		return this.fatLevel;
	}

	public void setFatLevel(Character fatLevel)
	{
		this.fatLevel = fatLevel;
	}

	public String getStatus()
	{
		return this.status;
	}

	public void setStatus(String status)
	{
		this.status = status;
	}

	public Integer getAfterNum()
	{
		return this.afterNum;
	}

	public void setAfterNum(Integer afterNum)
	{
		this.afterNum = afterNum;
	}

	public String getSampleVol()
	{
		return this.sampleVol;
	}

	public void setSampleVol(String sampleVol)
	{
		this.sampleVol = sampleVol;
	}

	public String getNumUnit()
	{
		return this.numUnit;
	}

	public void setNumUnit(String numUnit)
	{
		this.numUnit = numUnit;
	}

	public Integer getNums()
	{
		return this.nums;
	}

	public void setNums(Integer nums)
	{
		this.nums = nums;
	}

	public Character getFeeId()
	{
		return this.feeId;
	}

	public void setFeeId(Character feeId)
	{
		this.feeId = feeId;
	}

	public Character getReportId()
	{
		return this.reportId;
	}

	public void setReportId(Character reportId)
	{
		this.reportId = reportId;
	}

	public String getPraRes1()
	{
		return this.praRes1;
	}

	public void setPraRes1(String praRes1)
	{
		this.praRes1 = praRes1;
	}

	public String getPraRes2()
	{
		return this.praRes2;
	}

	public void setPraRes2(String praRes2)
	{
		this.praRes2 = praRes2;
	}

	public Character getOkId()
	{
		return this.okId;
	}

	public void setOkId(Character okId)
	{
		this.okId = okId;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public String getYuanshibianhao()
	{
		return this.yuanshibianhao;
	}

	public void setYuanshibianhao(String yuanshibianhao)
	{
		this.yuanshibianhao = yuanshibianhao;
	}

	public String getXingbie()
	{
		return this.xingbie;
	}

	public void setXingbie(String xingbie)
	{
		this.xingbie = xingbie;
	}

	public Date getCaiyangriqi()
	{
		return this.caiyangriqi;
	}

	public void setCaiyangriqi(Date caiyangriqi)
	{
		this.caiyangriqi = caiyangriqi;
	}

	public Date getShouyangriqi()
	{
		return this.shouyangriqi;
	}

	public void setShouyangriqi(Date shouyangriqi)
	{
		this.shouyangriqi = shouyangriqi;
	}

	public Date getJianceriqi()
	{
		return this.jianceriqi;
	}

	public void setJianceriqi(Date jianceriqi)
	{
		this.jianceriqi = jianceriqi;
	}

	public String getShijian()
	{
		return this.shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}

	public String getJiancexiangmu()
	{
		return this.jiancexiangmu;
	}

	public void setJiancexiangmu(String jiancexiangmu)
	{
		this.jiancexiangmu = jiancexiangmu;
	}

	public Set<SamplePic> getSamplePics()
	{
		return this.samplePics;
	}

	public void setSamplePics(Set<SamplePic> samplePics)
	{
		this.samplePics = samplePics;
	}

}
