package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Sterilizing generated by hbm2java
 */
public class Sterilizing implements java.io.Serializable
{

	private int id;
	private Date stlDate;
	private Character safeId;
	private Character stlFace;
	private Character stlTool;
	private Character stlSeat;
	private Character stlBottle;
	private Character stlInner;
	private String operator;
	private String remark;
	private String recordName;
	private Date recordTime;

	public Sterilizing()
	{
	}

	public Sterilizing(int id, Date stlDate)
	{
		this.id = id;
		this.stlDate = stlDate;
	}

	public Sterilizing(int id, Date stlDate, Character safeId, Character stlFace, Character stlTool, Character stlSeat,
			Character stlBottle, Character stlInner, String operator, String remark, String recordName, Date recordTime)
	{
		this.id = id;
		this.stlDate = stlDate;
		this.safeId = safeId;
		this.stlFace = stlFace;
		this.stlTool = stlTool;
		this.stlSeat = stlSeat;
		this.stlBottle = stlBottle;
		this.stlInner = stlInner;
		this.operator = operator;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Date getStlDate()
	{
		return this.stlDate;
	}

	public void setStlDate(Date stlDate)
	{
		this.stlDate = stlDate;
	}

	public Character getSafeId()
	{
		return this.safeId;
	}

	public void setSafeId(Character safeId)
	{
		this.safeId = safeId;
	}

	public Character getStlFace()
	{
		return this.stlFace;
	}

	public void setStlFace(Character stlFace)
	{
		this.stlFace = stlFace;
	}

	public Character getStlTool()
	{
		return this.stlTool;
	}

	public void setStlTool(Character stlTool)
	{
		this.stlTool = stlTool;
	}

	public Character getStlSeat()
	{
		return this.stlSeat;
	}

	public void setStlSeat(Character stlSeat)
	{
		this.stlSeat = stlSeat;
	}

	public Character getStlBottle()
	{
		return this.stlBottle;
	}

	public void setStlBottle(Character stlBottle)
	{
		this.stlBottle = stlBottle;
	}

	public Character getStlInner()
	{
		return this.stlInner;
	}

	public void setStlInner(Character stlInner)
	{
		this.stlInner = stlInner;
	}

	public String getOperator()
	{
		return this.operator;
	}

	public void setOperator(String operator)
	{
		this.operator = operator;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

}
