package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SysMenu generated by hbm2java
 */
public class SysMenu implements java.io.Serializable
{

	private int id;
	private String name;
	private Integer parentId;
	private String url;
	private Character folderId;
	private Integer levelId;
	private Character buttonId;
	private String img;
	private Integer orderNo;
	private String remark;
	private String recordName;
	private Date recordTime;
	private Set<SysRoleRight> sysRoleRights = new HashSet<SysRoleRight>(0);

	public SysMenu()
	{
	}

	public SysMenu(int id, String name)
	{
		this.id = id;
		this.name = name;
	}

	public SysMenu(int id, String name, Integer parentId, String url, Character folderId, Integer levelId,
			Character buttonId, String img, Integer orderNo, String remark, String recordName, Date recordTime,
			Set<SysRoleRight> sysRoleRights)
	{
		this.id = id;
		this.name = name;
		this.parentId = parentId;
		this.url = url;
		this.folderId = folderId;
		this.levelId = levelId;
		this.buttonId = buttonId;
		this.img = img;
		this.orderNo = orderNo;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
		this.sysRoleRights = sysRoleRights;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Integer getParentId()
	{
		return this.parentId;
	}

	public void setParentId(Integer parentId)
	{
		this.parentId = parentId;
	}

	public String getUrl()
	{
		return this.url;
	}

	public void setUrl(String url)
	{
		this.url = url;
	}

	public Character getFolderId()
	{
		return this.folderId;
	}

	public void setFolderId(Character folderId)
	{
		this.folderId = folderId;
	}

	public Integer getLevelId()
	{
		return this.levelId;
	}

	public void setLevelId(Integer levelId)
	{
		this.levelId = levelId;
	}

	public Character getButtonId()
	{
		return this.buttonId;
	}

	public void setButtonId(Character buttonId)
	{
		this.buttonId = buttonId;
	}

	public String getImg()
	{
		return this.img;
	}

	public void setImg(String img)
	{
		this.img = img;
	}

	public Integer getOrderNo()
	{
		return this.orderNo;
	}

	public void setOrderNo(Integer orderNo)
	{
		this.orderNo = orderNo;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public Set<SysRoleRight> getSysRoleRights()
	{
		return this.sysRoleRights;
	}

	public void setSysRoleRights(Set<SysRoleRight> sysRoleRights)
	{
		this.sysRoleRights = sysRoleRights;
	}

}
