package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SysRole generated by hbm2java
 */
public class SysRole implements java.io.Serializable
{

	private int id;
	private String name;
	private String remark;
	private String recordName;
	private Date recordTime;
	private Set<SysRoleRight> sysRoleRights = new HashSet<SysRoleRight>(0);
	private Set<SysUser> sysUsers = new HashSet<SysUser>(0);

	public SysRole()
	{
	}

	public SysRole(int id, String name)
	{
		this.id = id;
		this.name = name;
	}

	public SysRole(int id, String name, String remark, String recordName, Date recordTime,
			Set<SysRoleRight> sysRoleRights, Set<SysUser> sysUsers)
	{
		this.id = id;
		this.name = name;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
		this.sysRoleRights = sysRoleRights;
		this.sysUsers = sysUsers;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public Set<SysRoleRight> getSysRoleRights()
	{
		return this.sysRoleRights;
	}

	public void setSysRoleRights(Set<SysRoleRight> sysRoleRights)
	{
		this.sysRoleRights = sysRoleRights;
	}

	public Set<SysUser> getSysUsers()
	{
		return this.sysUsers;
	}

	public void setSysUsers(Set<SysUser> sysUsers)
	{
		this.sysUsers = sysUsers;
	}

}
