package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * SysUser generated by hbm2java
 */
public class SysUser implements java.io.Serializable
{

	private int id;
	private SysRole sysRole;
	private String code;
	private String name;
	private String password;
	private String telephone;
	private String mobile;
	private String remark;
	private String recordName;
	private Date recordTime;
	private Character labId;
	private Character reportId;
	private Integer deptId;
	private String fileName;

	public SysUser()
	{
	}

	public SysUser(int id, SysRole sysRole, String code, String name, String password)
	{
		this.id = id;
		this.sysRole = sysRole;
		this.code = code;
		this.name = name;
		this.password = password;
	}

	public SysUser(int id, SysRole sysRole, String code, String name, String password, String telephone, String mobile,
			String remark, String recordName, Date recordTime, Character labId, Character reportId, Integer deptId,
			String fileName)
	{
		this.id = id;
		this.sysRole = sysRole;
		this.code = code;
		this.name = name;
		this.password = password;
		this.telephone = telephone;
		this.mobile = mobile;
		this.remark = remark;
		this.recordName = recordName;
		this.recordTime = recordTime;
		this.labId = labId;
		this.reportId = reportId;
		this.deptId = deptId;
		this.fileName = fileName;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public SysRole getSysRole()
	{
		return this.sysRole;
	}

	public void setSysRole(SysRole sysRole)
	{
		this.sysRole = sysRole;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getPassword()
	{
		return this.password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	public String getTelephone()
	{
		return this.telephone;
	}

	public void setTelephone(String telephone)
	{
		this.telephone = telephone;
	}

	public String getMobile()
	{
		return this.mobile;
	}

	public void setMobile(String mobile)
	{
		this.mobile = mobile;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getRecordName()
	{
		return this.recordName;
	}

	public void setRecordName(String recordName)
	{
		this.recordName = recordName;
	}

	public Date getRecordTime()
	{
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime)
	{
		this.recordTime = recordTime;
	}

	public Character getLabId()
	{
		return this.labId;
	}

	public void setLabId(Character labId)
	{
		this.labId = labId;
	}

	public Character getReportId()
	{
		return this.reportId;
	}

	public void setReportId(Character reportId)
	{
		this.reportId = reportId;
	}

	public Integer getDeptId()
	{
		return this.deptId;
	}

	public void setDeptId(Integer deptId)
	{
		this.deptId = deptId;
	}

	public String getFileName()
	{
		return this.fileName;
	}

	public void setFileName(String fileName)
	{
		this.fileName = fileName;
	}

}
