package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

/**
 * VAab generated by hbm2java
 */
public class VAab implements java.io.Serializable
{

	private VAabId id;

	public VAab()
	{
	}

	public VAab(VAabId id)
	{
		this.id = id;
	}

	public VAabId getId()
	{
		return this.id;
	}

	public void setId(VAabId id)
	{
		this.id = id;
	}

}
