package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

/**
 * VAboItem generated by hbm2java
 */
public class VAboItem implements java.io.Serializable
{

	private VAboItemId id;

	public VAboItem()
	{
	}

	public VAboItem(VAboItemId id)
	{
		this.id = id;
	}

	public VAboItemId getId()
	{
		return this.id;
	}

	public void setId(VAboItemId id)
	{
		this.id = id;
	}

}
