package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * VFa generated by hbm2java
 */
public class VFa implements java.io.Serializable
{

	private VFaId id;

	public VFa()
	{
	}

	public VFa(VFaId id)
	{
		this.id = id;
	}

	public VFaId getId()
	{
		return this.id;
	}

	public void setId(VFaId id)
	{
		this.id = id;
	}

}
