package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * VRa generated by hbm2java
 */
public class VRa implements java.io.Serializable
{

	private VRaId id;

	public VRa()
	{
	}

	public VRa(VRaId id)
	{
		this.id = id;
	}

	public VRaId getId()
	{
		return this.id;
	}

	public void setId(VRaId id)
	{
		this.id = id;
	}

}
