package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

/**
 * VRt generated by hbm2java
 */
public class VRt implements java.io.Serializable
{

	private VRtId id;

	public VRt()
	{
	}

	public VRt(VRtId id)
	{
		this.id = id;
	}

	public VRtId getId()
	{
		return this.id;
	}

	public void setId(VRtId id)
	{
		this.id = id;
	}

}
