package deefw;
// Generated 2015-12-10 14:28:51 by Hibernate Tools 4.3.1.Final

/**
 * VRtId generated by hbm2java
 */
public class VRtId implements java.io.Serializable
{

	private String reagentName;
	private String method;
	private String res1;
	private String res2;
	private String res3;
	private String res4;
	private String res5;
	private String res6;
	private String res7;
	private String res8;
	private String res9;
	private String res10;
	private String res11;
	private String result;
	private char reportRes;
	private String methodName;
	private int billId;
	private int id;

	public VRtId()
	{
	}

	public VRtId(char reportRes, int billId, int id)
	{
		this.reportRes = reportRes;
		this.billId = billId;
		this.id = id;
	}

	public VRtId(String reagentName, String method, String res1, String res2, String res3, String res4, String res5,
			String res6, String res7, String res8, String res9, String res10, String res11, String result,
			char reportRes, String methodName, int billId, int id)
	{
		this.reagentName = reagentName;
		this.method = method;
		this.res1 = res1;
		this.res2 = res2;
		this.res3 = res3;
		this.res4 = res4;
		this.res5 = res5;
		this.res6 = res6;
		this.res7 = res7;
		this.res8 = res8;
		this.res9 = res9;
		this.res10 = res10;
		this.res11 = res11;
		this.result = result;
		this.reportRes = reportRes;
		this.methodName = methodName;
		this.billId = billId;
		this.id = id;
	}

	public String getReagentName()
	{
		return this.reagentName;
	}

	public void setReagentName(String reagentName)
	{
		this.reagentName = reagentName;
	}

	public String getMethod()
	{
		return this.method;
	}

	public void setMethod(String method)
	{
		this.method = method;
	}

	public String getRes1()
	{
		return this.res1;
	}

	public void setRes1(String res1)
	{
		this.res1 = res1;
	}

	public String getRes2()
	{
		return this.res2;
	}

	public void setRes2(String res2)
	{
		this.res2 = res2;
	}

	public String getRes3()
	{
		return this.res3;
	}

	public void setRes3(String res3)
	{
		this.res3 = res3;
	}

	public String getRes4()
	{
		return this.res4;
	}

	public void setRes4(String res4)
	{
		this.res4 = res4;
	}

	public String getRes5()
	{
		return this.res5;
	}

	public void setRes5(String res5)
	{
		this.res5 = res5;
	}

	public String getRes6()
	{
		return this.res6;
	}

	public void setRes6(String res6)
	{
		this.res6 = res6;
	}

	public String getRes7()
	{
		return this.res7;
	}

	public void setRes7(String res7)
	{
		this.res7 = res7;
	}

	public String getRes8()
	{
		return this.res8;
	}

	public void setRes8(String res8)
	{
		this.res8 = res8;
	}

	public String getRes9()
	{
		return this.res9;
	}

	public void setRes9(String res9)
	{
		this.res9 = res9;
	}

	public String getRes10()
	{
		return this.res10;
	}

	public void setRes10(String res10)
	{
		this.res10 = res10;
	}

	public String getRes11()
	{
		return this.res11;
	}

	public void setRes11(String res11)
	{
		this.res11 = res11;
	}

	public String getResult()
	{
		return this.result;
	}

	public void setResult(String result)
	{
		this.result = result;
	}

	public char getReportRes()
	{
		return this.reportRes;
	}

	public void setReportRes(char reportRes)
	{
		this.reportRes = reportRes;
	}

	public String getMethodName()
	{
		return this.methodName;
	}

	public void setMethodName(String methodName)
	{
		this.methodName = methodName;
	}

	public int getBillId()
	{
		return this.billId;
	}

	public void setBillId(int billId)
	{
		this.billId = billId;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VRtId))
			return false;
		VRtId castOther = (VRtId) other;

		return ((this.getReagentName() == castOther.getReagentName()) || (this.getReagentName() != null
				&& castOther.getReagentName() != null && this.getReagentName().equals(castOther.getReagentName())))
				&& ((this.getMethod() == castOther.getMethod()) || (this.getMethod() != null
						&& castOther.getMethod() != null && this.getMethod().equals(castOther.getMethod())))
				&& ((this.getRes1() == castOther.getRes1()) || (this.getRes1() != null && castOther.getRes1() != null
						&& this.getRes1().equals(castOther.getRes1())))
				&& ((this.getRes2() == castOther.getRes2()) || (this.getRes2() != null && castOther.getRes2() != null
						&& this.getRes2().equals(castOther.getRes2())))
				&& ((this.getRes3() == castOther.getRes3()) || (this.getRes3() != null && castOther.getRes3() != null
						&& this.getRes3().equals(castOther.getRes3())))
				&& ((this.getRes4() == castOther.getRes4()) || (this.getRes4() != null && castOther.getRes4() != null
						&& this.getRes4().equals(castOther.getRes4())))
				&& ((this.getRes5() == castOther.getRes5()) || (this.getRes5() != null && castOther.getRes5() != null
						&& this.getRes5().equals(castOther.getRes5())))
				&& ((this.getRes6() == castOther.getRes6()) || (this.getRes6() != null && castOther.getRes6() != null
						&& this.getRes6().equals(castOther.getRes6())))
				&& ((this.getRes7() == castOther.getRes7()) || (this.getRes7() != null && castOther.getRes7() != null
						&& this.getRes7().equals(castOther.getRes7())))
				&& ((this.getRes8() == castOther.getRes8()) || (this.getRes8() != null && castOther.getRes8() != null
						&& this.getRes8().equals(castOther.getRes8())))
				&& ((this.getRes9() == castOther.getRes9()) || (this.getRes9() != null && castOther.getRes9() != null
						&& this.getRes9().equals(castOther.getRes9())))
				&& ((this.getRes10() == castOther.getRes10()) || (this.getRes10() != null
						&& castOther.getRes10() != null && this.getRes10().equals(castOther.getRes10())))
				&& ((this.getRes11() == castOther.getRes11()) || (this.getRes11() != null
						&& castOther.getRes11() != null && this.getRes11().equals(castOther.getRes11())))
				&& ((this.getResult() == castOther.getResult()) || (this.getResult() != null
						&& castOther.getResult() != null && this.getResult().equals(castOther.getResult())))
				&& (this.getReportRes() == castOther.getReportRes())
				&& ((this.getMethodName() == castOther.getMethodName()) || (this.getMethodName() != null
						&& castOther.getMethodName() != null && this.getMethodName().equals(castOther.getMethodName())))
				&& (this.getBillId() == castOther.getBillId()) && (this.getId() == castOther.getId());
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result + (getReagentName() == null ? 0 : this.getReagentName().hashCode());
		result = 37 * result + (getMethod() == null ? 0 : this.getMethod().hashCode());
		result = 37 * result + (getRes1() == null ? 0 : this.getRes1().hashCode());
		result = 37 * result + (getRes2() == null ? 0 : this.getRes2().hashCode());
		result = 37 * result + (getRes3() == null ? 0 : this.getRes3().hashCode());
		result = 37 * result + (getRes4() == null ? 0 : this.getRes4().hashCode());
		result = 37 * result + (getRes5() == null ? 0 : this.getRes5().hashCode());
		result = 37 * result + (getRes6() == null ? 0 : this.getRes6().hashCode());
		result = 37 * result + (getRes7() == null ? 0 : this.getRes7().hashCode());
		result = 37 * result + (getRes8() == null ? 0 : this.getRes8().hashCode());
		result = 37 * result + (getRes9() == null ? 0 : this.getRes9().hashCode());
		result = 37 * result + (getRes10() == null ? 0 : this.getRes10().hashCode());
		result = 37 * result + (getRes11() == null ? 0 : this.getRes11().hashCode());
		result = 37 * result + (getResult() == null ? 0 : this.getResult().hashCode());
		result = 37 * result + this.getReportRes();
		result = 37 * result + (getMethodName() == null ? 0 : this.getMethodName().hashCode());
		result = 37 * result + this.getBillId();
		result = 37 * result + this.getId();
		return result;
	}

}
