package deefw;
// Generated 2015-12-29 13:42:08 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Yangbenjushou generated by hbm2java
 */
public class Yangbenjushou implements java.io.Serializable
{

	private int id;
	private int jiancedanid;
	private String xingming;
	private String xingbie;
	private String gonghuanguanxi;
	private String songjiandanwei;
	private String yangbenleixing;
	private String shijian;
	private String shouyangzhe;
	private String jushouyuanyin;
	private String chulifangshi;
	private String zaicishouyangshijian;
	private String beizhu;
	private String yangguanshu;
	private Date caiyangriqi;
	private Date zaicishouyangriqi;
	private Date shouyangriqi;
	private String yuanyin;

	public Yangbenjushou()
	{
	}

	public Yangbenjushou(int id, int jiancedanid)
	{
		this.id = id;
		this.jiancedanid = jiancedanid;
	}

	public Yangbenjushou(int id, int jiancedanid, String xingming, String xingbie, String gonghuanguanxi,
			String songjiandanwei, String yangbenleixing, String shijian, String shouyangzhe, String jushouyuanyin,
			String chulifangshi, String zaicishouyangshijian, String beizhu, String yangguanshu, Date caiyangriqi,
			Date zaicishouyangriqi, Date shouyangriqi, String yuanyin)
	{
		this.id = id;
		this.jiancedanid = jiancedanid;
		this.xingming = xingming;
		this.xingbie = xingbie;
		this.gonghuanguanxi = gonghuanguanxi;
		this.songjiandanwei = songjiandanwei;
		this.yangbenleixing = yangbenleixing;
		this.shijian = shijian;
		this.shouyangzhe = shouyangzhe;
		this.jushouyuanyin = jushouyuanyin;
		this.chulifangshi = chulifangshi;
		this.zaicishouyangshijian = zaicishouyangshijian;
		this.beizhu = beizhu;
		this.yangguanshu = yangguanshu;
		this.caiyangriqi = caiyangriqi;
		this.zaicishouyangriqi = zaicishouyangriqi;
		this.shouyangriqi = shouyangriqi;
		this.yuanyin = yuanyin;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public int getJiancedanid()
	{
		return this.jiancedanid;
	}

	public void setJiancedanid(int jiancedanid)
	{
		this.jiancedanid = jiancedanid;
	}

	public String getXingming()
	{
		return this.xingming;
	}

	public void setXingming(String xingming)
	{
		this.xingming = xingming;
	}

	public String getXingbie()
	{
		return this.xingbie;
	}

	public void setXingbie(String xingbie)
	{
		this.xingbie = xingbie;
	}

	public String getGonghuanguanxi()
	{
		return this.gonghuanguanxi;
	}

	public void setGonghuanguanxi(String gonghuanguanxi)
	{
		this.gonghuanguanxi = gonghuanguanxi;
	}

	public String getSongjiandanwei()
	{
		return this.songjiandanwei;
	}

	public void setSongjiandanwei(String songjiandanwei)
	{
		this.songjiandanwei = songjiandanwei;
	}

	public String getYangbenleixing()
	{
		return this.yangbenleixing;
	}

	public void setYangbenleixing(String yangbenleixing)
	{
		this.yangbenleixing = yangbenleixing;
	}

	public String getShijian()
	{
		return this.shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}

	public String getShouyangzhe()
	{
		return this.shouyangzhe;
	}

	public void setShouyangzhe(String shouyangzhe)
	{
		this.shouyangzhe = shouyangzhe;
	}

	public String getJushouyuanyin()
	{
		return this.jushouyuanyin;
	}

	public void setJushouyuanyin(String jushouyuanyin)
	{
		this.jushouyuanyin = jushouyuanyin;
	}

	public String getChulifangshi()
	{
		return this.chulifangshi;
	}

	public void setChulifangshi(String chulifangshi)
	{
		this.chulifangshi = chulifangshi;
	}

	public String getZaicishouyangshijian()
	{
		return this.zaicishouyangshijian;
	}

	public void setZaicishouyangshijian(String zaicishouyangshijian)
	{
		this.zaicishouyangshijian = zaicishouyangshijian;
	}

	public String getBeizhu()
	{
		return this.beizhu;
	}

	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}

	public String getYangguanshu()
	{
		return this.yangguanshu;
	}

	public void setYangguanshu(String yangguanshu)
	{
		this.yangguanshu = yangguanshu;
	}

	public Date getCaiyangriqi()
	{
		return this.caiyangriqi;
	}

	public void setCaiyangriqi(Date caiyangriqi)
	{
		this.caiyangriqi = caiyangriqi;
	}

	public Date getZaicishouyangriqi()
	{
		return this.zaicishouyangriqi;
	}

	public void setZaicishouyangriqi(Date zaicishouyangriqi)
	{
		this.zaicishouyangriqi = zaicishouyangriqi;
	}

	public Date getShouyangriqi()
	{
		return this.shouyangriqi;
	}

	public void setShouyangriqi(Date shouyangriqi)
	{
		this.shouyangriqi = shouyangriqi;
	}

	public String getYuanyin()
	{
		return this.yuanyin;
	}

	public void setYuanyin(String yuanyin)
	{
		this.yuanyin = yuanyin;
	}

}
